#+TITLE: Jeff's Emacs config
#+AUTHOR: Jeff Stautz
#+EMAIL: jeff@jeffstautz.com
#+LANGUAGE:  en
#+OPTIONS: toc:nil num:t ^:nil

#+begin_quote
People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen -- the editor should get used to us.

-- [[http://blog.vivekhaldar.com/post/31970017734/new-frontiers-in-text-editing][Vivek Hadlar]]
#+end_quote

#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

** What is this?
:PROPERTIES:
:CUSTOM_ID: what_is_this
:END:

It's a [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] version of my Emacs config files.

My current setup borrows liberally from Emacs users far smarter than I am, including:
- [[http://doc.norang.ca/org-mode.html][Bernt Hansen]] 
- [[https://github.com/eschulte/emacs24-starter-kit][Eric Schulte]]
- [[https://github.com/magnars/.emacs.d][Magnar Sveen]]
- [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua]]
- [[https://github.com/technomancy/dotfiles][Phil Hagelberg]]
- [[https://github.com/bodil/emacs.d][Bodil Stokke]]
- [[http://www.masteringemacs.org/][Mickey Petersen]]
- And a ton of others. 

Props and praises are scattered throughout my config in places where I can remember who I stole something from.

** What the hell is literate programming?
:PROPERTIES:
:CUSTOM_ID: what_is_literate
:END: 

Short answer: instead of writing separate documentation, the documentation /contains/ the program. 

Or as Knuth puts it:

#+begin_quote 
Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to humans what we want the computer to do.

-- Donald E. Knuth, Literate Programming, 1984
#+end_quote

The document you're reading now is an [[http://org-mode.org][org-mode]] text file[fn:1] that contains both code and documentation. 

On startup, emacs pulls out ("tangles") the code snippets in this file and uses them to configure the editor.

[fn:1] Okay, technically you're reading HTML that's exported from the org-mode text file. The point is that the *source file* that I edit when I update my Emacs config *is the documentation.* The elisp is compiled (tangled) from the documentation org-mode files. Org-mode files can be exported in a number of nifty formats, including HTML.

-------------------------------------

** Why use literate programming for my Emacs config?
:PROPERTIES:
:CUSTOM_ID: why-literate
:END:

It's an experiment. We'll see how well it works out.

I've been inspired by [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua's literate emacs config]], as well as by [[http://doc.norang.ca/org-mode.html][Bernt Hansen's amazingly thorough and detailed documentation of his org-mode setup]].

Using a literate programming approach has a number of advantages that appeal to me:

1. *Better organization of my .emacs lisp files*
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure.
   - I'm able to add headers and subsections to better organize my code -- way better than using giant banner-style comment blocks or squirreling things away in separate files all over the place.
   - My configuration is easier to read and understand.
2. *I'm better able to follow my own thought processes.*
   - Code is organized according to how I think, not how the interpreter thinks -- I can explain code snippets in an order that makes sense to me, and org-babel later compiles these into the correct order.
   - Explanations take priority, code is secondary.
   - When I revisit code I wrote ten years ago, I have a hope of understanding not just what it does, but /what the hell I was thinking./
3. *Sharing my setup is easier*
   - Org-mode's publishing features mean that it's pretty simple to export my documentation and publish it.
   - I have one file that generates nice-looking documentation and the code itself.
   - Even better: more detailed explanations of my code mean it's easier for others to understand it and benefit from it.
     
** Disclaimers and Warnings
:PROPERTIES:
:CUSTOM_ID: disclaimer
:END:

You /don't/ want to try and use my configs straight out of the box. 

- This is a perpetual work in progress. 
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies, and there are probably a bunch of undocumented dependencies.
- Requires Emacs 24.3. Only tested on Mac OS X.
- I'm not responsible if any of this blows up on you.

** License
:PROPERTIES:
:CUSTOM_ID: license
:END:

I don't actually need a license for this, but I feel /way/ cooler having one here.

#+begin_example
Copyright (C)  2014  Jeff Stautz

Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts.
  
Code in this document is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.
  
This code is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
#+end_example 

This document (including HTML format or raw org-mode format) is licensed under the GNU Free Documentation License version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

The code examples and CSS stylesheets are licensed under the GNU General Public License v3 or later (http://www.gnu.org/licenses/gpl.html).


* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

#+begin_quote
Accio Emacs packages!

-- Harry Potter
#+end_quote

** Clone this repo into your .emacs.d/ 

You probably want to back up your current config first.

#+begin_example
git clone https://github.com/jstautz/.emacs.d ~/.emacs.d
#+end_example

** Run the install script

Special thanks to [[http://www.swaroopch.com/2013/10/17/emacs-configuration-tutorial/][Swaroop C H]] for this script.

#+begin_example
cd ~/.emacs.d/
./install.sh
#+end_example

This will:
- Install [[http://cask.github.io/][Cask]] if you don't already have it installed
- Add the ~/.cask directory to your $PATH
  - note: assumes you're using bash. If you're using another shell, edit install.sh before running
- Runs =cask install= to install packages listed in my Cask file, along with any dependencies

=cask install= will hit various Emacs package repositories (ELPA, MELPA, Marmalade, and Org) and download packages for you. Magic!

** Fire up Emacs

Packages installed via Cask should be in your load path, and you should be ready to rock. 

If you're *not* ready to rock at this point... sorry. Don't say I didn't [[Disclaimers and Warnings][warn you]].

* Structure 
:PROPERTIES:
:CUSTOM_ID: structure
:END:

A couple of details about how all this works:

** =init.el=

This is the first file that Emacs loads on startup. It bootstraps the rest of my config by loading it via org-babel.

My init.el currently looks like this:

#+begin_src emacs-lisp :tangle no
;; Assume current directory is the dot-emacs directory and add to load-path
(setq dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name))))

;; Load cask and activate it.
;; https://github.com/cask/cask
(require 'cask "~/.cask/cask.el")
(cask-initialize)

;; If emacs-init.el is *newer* than emacs-init.org, then load the *.el file directly.
;; Otherwise, tangle the *.org file and load my config.
(if (> (string-to-int (shell-command-to-string "stat -f \"%m\" ~/.emacs.d/emacs-init.el"))
       (string-to-int (shell-command-to-string "stat -f \"%m\" ~/.emacs.d/emacs-init.org")))
      (load-file (expand-file-name "emacs-init.el" dotemacs-dir))
    (org-babel-load-file (expand-file-name "emacs-init.org" dotemacs-dir)))

#+end_src

That's it.

The important part is that last s-expression: 

#+begin_src emacs-lisp :tangle no
(org-babel-load-file (expand-file-name "emacs-init.org" dotemacs-dir)
#+end_src

This line calls org-babel to export ("tangle") the code blocks from the =emacs-init.org= file into a file called =emacs-init.el=, then load that file.

[[http://orgmode.org/worg/org-contrib/babel/][Org-babel is Merlin-level wizardry.]] Eric Schulte, Dan Davison, and everyone who's worked on it all deserve medals. 

The =if= statement wrapping this =org-babel-load-file= expression will improve load time if my config hasn't changed. If my "tangled" =emacs-init.el= file is newer than the most recent changes to =emacs-init.org=, then I load the .el file directly.

** =emacs-init.org=

The emacs-init.org file is the meat of my emacs config. It's also the document you're reading right now.

When this document is tangled and loaded by org-babel, all the elisp code snippets contained within it are re-arranged and loaded. 

That re-arranging bit is important. Expressions in my config file need to be in a particular order for Emacs to understand them. But I also want to be able to document them in =emacs-init.org= in a totally different order -- one that makes sense to a human reader.

I can define that Emacs-friendly code order here, using "noweb" syntax[fn:2], which looks something like:

#+begin_src emacs-lisp :tangle yes :noweb tangle
<<Prerequisites and setup -- load basic support libraries, set some useful variables>>
<<Load and configure Cask & Pallet to load packages>>
<<General Editor Settings: UI, files, navigation, editing, scrolling>>

<<Load some editor customizations>>
<<Set custom keybindings>>

<<Post-flight: load Emacs desktop and start server>>
#+end_src

(removed <<Load a bunch of custom functions>> from this temporarily.)

When I tangle this file, the noweb headers above will be expanded to the matching sections of elisp. 

I try to treat the resulting =emacs-init.el= file like /compiled code/. It's the machine-readable file that I never really look at. 

Any edits or changes, even if they're experimental, are made in the org-mode files instead of directly in the .el files. This way, I'm ensuring my documentation always stays up to date. I'm explaining changes as I make them rather than documenting them after the fact.

[fn:2] Found a possible bug with noweb and comments. 

If I set =comments noweb=, the links generated in the code don't seem to correctly link. Noweb-referenced code sections have empty file/search links. It would be best if they linked to the custom_id property of the subtree they're in. Might be something I can hack on and fix later.

-------------------------------------

** Loading packages 
:PROPERTIES:
:noweb-ref: Load and configure Cask & Pallet to load packages
:END:

Back in the dark ages, I would find third-party elisp packages on the interwebs and install them manually. This got nasty pretty quickly.

    - My emacs repo got bloated and disorganized
    - I could never rememember where I grabbed packages from
    - Updating packages was a chore

Emacs 24 introduced a really nice package management system. I used it for a while on its own, then supplemented it with [[http://cask.github.io/][Cask]], [[https://github.com/rdallasgray/pallet][Pallet]], and [[https://github.com/jwiegley/use-package][use-package]].

*** Cask

I don't keep *any* of my packages under version control at the moment. If I install Emacs config from scratch, my installation script + Cask will download and load all the packages I need.

#+name: package-cask
#+begin_src emacs-lisp 
(require 'cask "~/.cask/cask.el")
(cask-initialize)
#+end_src

*** use-package
 
John Wiegley's use-package lets me nicely isolate loading packages and their configurations. It handles a lot of things for me out of the box, including:

- Handling missing packages without choking
- Initializing packages
- Set keybindings
- Deferring configuration elisp until after a package actually gets used
- And more!

#+name: package-use-package
#+begin_src emacs-lisp 
(require 'use-package)
#+end_src

*** Pallet

If I install a new package via =M-x list-packages=, Pallet automatically updates my Cask file and keeps everything in sync. This way I don't lose track of anything installed via package.el -- it's all still in my config and can be pulled down via =cask install=. 

#+name: package-use-package
#+begin_src emacs-lisp 
(use-package pallet)
#+end_src
* What I use Emacs for
:PROPERTIES:
:CUSTOM_ID: what-i-do-in-emacs
:END:

#+begin_quote
This is my rifle. There are many like it, but this one is mine.

--Major General William H. Rupertus, "The Rifleman's Creed," 1942
#+end_quote

In order to understand why I've configured things the way I did, it might help to understand some things I do in Emacs.

** Org-mode

I spend 90% of my time in Emacs inside [[http://orgmode.org/][org-mode]]. 

I've been using it for several years for taking notes, planning, writing, and tracking my to-do lists. I've got a [[file:./init-org.org][whole section of my Emacs config dedicated to the ins and outs of my org-mode configuration.]]

It's gnarly. It's complicated. It involves a lot of yak-shaving. It's ripe for refactoring. But it /works/ for me. 

** Writing Fiction

For the last 9 years, I've done most of my writing, editing, and revising in plain text within Emacs.

Sometimes I work in [[https://daringfireball.net/projects/markdown/][Markdown syntax]] and view the formatted version of my stories in [[http://markedapp.com/][Marked.app]].

Other times I write using minimal [[http://www.latex-project.org/][LaTeX markup]], which I then run through a perl script to add full LaTeX document headers for exporting.

The details of [[file:./emacs-init.org][how I use Emacs for fiction writing are documented later in this file]]. 

** Programming

Unlike most Emacs users, I'm not a professional software engineer. 

I've done a bunch of development work in the past, and I enjoy messing around in code occasionally. I dabble. I pretend like I know what I'm doing. But I'm nowhere near professional.

[[http://hootsuite.com/careers/][I work with a ton of talented engineers every day at HootSuite]] and they constantly inspire me to learn more, try more, and hack more. 

When I grow up maybe I'll be an engineer.

A couple of languages I work with in Emacs:

- I work with Emacs lisp quite a bit (of course)
- I'm learning python
- I play around with javascript (and HTML/CSS, obviously)

[[file::./emacs-init.org][My Emacs settings for software development]] should be taken with several grains of salt -- these parts of my config aren't very mature and I'm probably doing everything wrong.

** Manipulating files and text of all kinds

Macros, mutli-line editing, directory editing, remote editing over SSH... Emacs is my Swiss Army Knife for text transformations. 

[[file:./emacs-init.org][There are large chunks of my config]] that deal with sharpening various blades of said Swiss Army Knife.

* General Editor Settings
:PROPERTIES:
:noweb-ref: General Editor Settings: UI, files, navigation, editing, scrolling
:END:

** Interface tweaks

I know, I know. Emacs doesn't have much of an interface to begin with. 

Even so, there are a couple of changes I like to make in order to make things a little cleaner.

*** Remove distracting UI elements

Emacs comes with a fat ugly toolbar turned on by default. It's seriously gross looking. 

Turning it off is one of the first things I do.

#+name: UI-toolbar
#+begin_src emacs-lisp 
(tool-bar-mode -1)
#+end_src

I don't really use the side fringe at all, so I set to a colour that blends into the buffer background. I happen to use Emacs with dark text on a white background, so I set the fringe to white. 

#+name: UI-fringe
#+begin_src emacs-lisp 
(custom-set-faces '(fringe ((t (:background"white")))))
#+end_src

Scroll bars are also pretty useless in this age of scroll wheels and trackpads, so I turn that off as well.

The only *good* part about a scroll bar? Its size and position give you a quick visual indication of how far down in the current file you are, and how large the file is.

I make up for this by [[File position][displaying a position indicator in my modeline]]-- I'll explain that setup a bit further down.

#+name: UI-fringe
#+begin_src emacs-lisp 
(scroll-bar-mode -1)

#+end_src

*** Hide welcome messages

We're all professionals, here. We know what we're doing. 

So let's ditch the splash screen, the startup message, and the default text on the scratch buffer:

#+name: UI-splash
#+begin_src emacs-lisp 
(setq inhibit-splash-screen 1)               
(setq initial-scratch-message "")
(setq inhibit-startup-message t)

#+end_src 

*** Kill some annoyances

Seriously, screw the audible alert bell.

Let's set the ring-bell function to an empty function instead of the deafult (which is named, appropriately, =ding=).

Let's also turn on the visible-bell option so that the screen blinks/alerts me.

#+name: UI-bells
#+begin_src emacs-lisp 
(setq ring-bell-function (lambda ()))
(setq visible-bell 1)                        

#+end_src

Another obnoxious default to change: the requirement that you actually type the letters "y" "e" and "s" at a yes/no prompt. Whose dumb idea was that? 

This s-exp lets you just type "y" or "n" like in any other sane application:

#+name: UI-yorn
#+begin_src emacs-lisp 
(fset 'yes-or-no-p 'y-or-n-p)

#+end_src


*** Confirm before quitting Emacs

I want to make sure I don't accidentally kill Emacs. Ever. 

I do this by changing two things:

1) Unset =C-x C-c= so I don't hit it accidentally, and
2) Prompt me to confirm that I actually want to quit.

If I want to quit Emacs (gasp!) I now need to do it *very* deliberately via =M-x save-buffers-kill-emacs= and then confirm.

[[Emacsclient / Server][Good thing I rarely quit Emacs]].

#+name: UI-quit-emacs
#+begin_src emacs-lisp
(global-unset-key "\C-x\C-c")
(setq confirm-kill-emacs 'y-or-n-p)

#+end_src
*** Mode-line settings
**** Show both line and column numbers in mode-line

A basic feature of any decent text editor: show me what line number I'm on.

The column number display isn't as immediately useful, but it does come in handy.

#+name: UI-linum
#+begin_src emacs-lisp 
(line-number-mode 1)                         
(column-number-mode 1)

#+end_src

**** Smart-mode-line setup
I use smart-mode-line to pack a bunch of useful info into my mode line.

#+name: UI-smart-mode-line
#+begin_src emacs-lisp
  (use-package smart-mode-line
    :init
    (progn
#+end_src 

When use-package initializes smart-mode-line, I want to set up the theme and width right away. I like that the theme's called "respectful."

#+name: UI-sml-settings
#+begin_src emacs-lisp
      (setq sml/theme 'respectful
            sml/name-width 40
            sml/mode-width 40)
#+end_src

smart-mode-line has a useful feature that allows you to replace elements of a path with an abbreviation. So instead of seeing =/Users/jstautz/Documents/Work/filename.txt= in the modeline, I'll see =:Work:filename.txt=. 

#+name: UI-sml-replacer
#+begin_src emacs-lisp
      (setq sml/replacer-regexp-list
        (quote
         (("^~/org/" ":Org:")
          ("^~/\\.emacs\\.d/" ":ED:")
          ("^~/[Gg]it/" ":Git:")
          ("^~/Dropbox/Writing/01-composting/" ":Compost:")
          ("^~/Dropbox/Writing/02-draft_in_progress/" ":Drafts:")
          ("^~/Dropbox/Writing/03-revision_in_progress/" ":Revs:")
          ("^~/Dropbox/Writing/04-submitted/" ":Submitted:")
          ("^~/Dropbox/Writing/05-published/" ":Published:")
          ("^~/Dropbox/Writing/06-cold_storage/" ":ColdStore:")
          ("^~/Dropbox/Writing/" ":Writing:")
          ("^~/Dropbox/finance/taxes 2013/" ":Tax2013:")
          ("^~/Dropbox/finance/taxes 2014/" ":Tax2014:")
          ("^~/Dropbox/" ":DB:")
          ("^~/Documents/Writing/01-composting/" ":Compost:")
          ("^~/Documents/Writing/02-draft_in_progress/" ":Drafts:")
          ("^~/Documents/Writing/03-revision_in_progress/" ":Revs:")
          ("^~/Documents/Writing/04-submitted/" ":Submitted:")
          ("^~/Documents/Writing/05-published/" ":Published:")
          ("^~/Documents/Writing/06-cold_storage/" ":ColdStore:")
          ("^~/Documents/Writing/" ":Writing:")
          ("^~/Documents/" ":Docs:")
          ("^~/Documents/Work/" ":Work:")
          ("^~/dev" ":dev:")
          ("^~/Sites" ":www:")
          ("^~/Downloads/" ":DLs:"))))
#+end_src

Fire up smart-mode-line immediately:

#+name: UI-sml-setup
#+begin_src emacs-lisp
      (sml/setup)))

#+end_src
**** File position

Remember how I [[Remove distracting UI elements][turned off the scroll bar?]] The one useful purpose scroll-bars serve is to indicate your current position in the buffer. 

Luckily, smart-mode-line has us covered. It includes a built-in feature to display your current position in the buffer as a %. It will also indicate =Top= or =Bot= when you're at the top or bottom of the buffer.

Note that this indicator refers to *visible* screen space within the window. So if you're working in org-mode on a large file with a lot of folding, you may be able to see the bottom of the buffer within the window, even if you're at the top of the file.

**** Diminish.el

Also related to keeping my mode-line clean: diminish is a package that lets you replace the default major/minor mode indicators in the mode-line with shorter abbreviations (or hide them altogether).

#+name: UI-modeline-diminish
#+begin_src emacs-lisp
(use-package diminish)

#+end_src 

Even better, use-package supports diminsh options as part of the declaration when loading packages.

Diminish also features [[http://www.eskimo.com/~seldon/diminish.el][some of the best code comments in the universe]].

*** Force redisplay

If the =redisplay-dont-pause= variable is not set, then any keyboard/mouse event will stop a screen redraw to handle the input. Which I suppose made sense on older machines or slower networks.

On modern machines, turning this on should make the display feel faster.

Thanks to [[http://www.masteringemacs.org/articles/2011/10/02/improving-performance-emacs-display-engine/][Mickey Peterson for this one]].

#+name: UI-redisplay
#+begin_src emacs-lisp 
(setq redisplay-dont-pause t)

#+end_src

I believe this is now on by default in Emacs 24, so I may no longer need to set this explicitly.
** Backups & Trash settings

Emacs has some pretty useful features for auto-saving backups and integrating with the OS Trash / filesystem.

*** Set backup directory

One problem with the default auto-save in Emacs is that it peppers your working directories with duplicates of your files, e.g. =#init.el#= =init.el~=. Ugly. 

Let's tell Emacs to put all these auto-saves and backups into a more useful location:

#+name: backup-dir
#+begin_src emacs-lisp
(defvar backup-dir (concat home-dir ".emacs.backup/"))
(defvar autosave-dir (concat home-dir ".emacs.autosave/"))
(setq backup-directory-alist `((".*" . ,backup-dir)))
(setq auto-save-file-name-transforms `((".*" ,autosave-dir t)))

#+end_src

*** Backups + version control

You have to explicitly tell Emacs to keep saving backups of files if they're under version control. 

#+name: backup-vc
#+begin_src emacs-lisp
(setq vc-make-backup-files t)

#+end_src
*** ~/.Trash integration

Instead of just blowing files away, I want all file-deletion events in emacs to do a =mv file.txt ~/.Trash= rather than a simple =rm file.txt=. This is just another layer of protecting myself from myself.

#+name: backup-trashes
#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t)
(setq trash-directory (concat home-dir ".Trash/"))

#+end_src

** Basic Keyboard settings
*** Unset some default keybindings

First let's unset a couple of keybindings:
- Read-only-toggle is bound by default to =C-x C-q=. It's a useless command that I toggle by accident way too often.
- I also hit =F2= accidentally way too often.

#+name: keybindings-unsets
#+begin_src emacs-lisp 
  (global-unset-key "\C-x\C-q")
  (global-unset-key (kbd "<f2>"))     

#+end_src

*** Save and Undo

Now let's set a couple of bindings based on my muscle memory:

- Rebind M-s to save-buffer -- I never center lines

#+name: keybindings-save
#+begin_src emacs-lisp 
(global-set-key (kbd "M-s") 'save-buffer)
#+end_src 

- =C-z= is bound to iconify-frame by default, which I never use. Set it to undo instead.

#+name: keybindings-save
#+begin_src emacs-lisp 
(global-set-key (kbd "C-z") 'undo)     

#+end_src

*** Mac keyboard settings

I use Emacs on OS X and get my builds from http://emacsformacosx.com/. There are a couple of things I need to configure to make Emacs.app play nicely on a Mac.

First, I want to treat Command *and* Option keys as Meta in Emacs. I know, this is weird. I may eventually change one of these to Super or Hyper. But for now, I like having large target areas for hitting Meta, since I use it so often.

#+name: UI-mac-settings-meta
#+begin_src emacs-lisp 
(setq ns-alternate-modifier (quote meta))
(setq ns-command-modifier (quote meta))

#+end_src
*** Mouse settings

Emulate a three-button mouse for copy/paste/select:

#+name: UI-mac-settings-clipboard
#+begin_src emacs-lisp 
(setq mac-emulate-three-button-mouse t)

#+end_src
** Cursor and Scrolling
*** Highlight cursor location

I realize a lot of people hate blinking cursors, but I like them because:

- It lets me quickly find my cursor on a large screen
- The persistent blinking indicates Emacs is waiting for my input -- it's pushing me to write, to get shit done. 

#+name: UI-cursor
#+begin_src emacs-lisp 
(setq blink-cursor-mode t)
#+end_src

Another helpful inidicator: I like having my current line highlighted. =grey93= is nice and subtle against a white background.

#+name: UI-highlight-line
#+begin_src emacs-lisp 
(global-hl-line-mode 1)
(set-face-background 'hl-line "grey93")

#+end_src

*** Cursor scroll settings

Let's make buffer scrolling / paging a bit more sane.

By default, Emacs will recenter on the cursor when you scroll above / below the current viewable area. This leads to some disorienting jumping around.

Setting =scroll-conservatively= to a value > 100 means automatic scrolling will never center on the cursor.

#+name: UI-scroll-conserv
#+begin_src emacs-lisp 
(setq scroll-conservatively 1000)
#+end_src

The =scroll-margin= variable controls how close to the bottom/top edge of the frame I can get before the viewable area begins to scroll. I like to get right up to the bottom edge before scrolling.

#+name: UI-scroll-margin
#+begin_src emacs-lisp 
(setq scroll-margin 0)
#+end_src

I don't want to jump around at all when scrolling up or down.

And when I *do* page up or down, I want my cursor to be in the same position relative to the top and bottom of the frame.

This just makes sense: When I page up or down with =M-v= or =C-v= I shouldn't have to hunt for my cursor. I should still be looking at it.

#+name: UI-scroll-agg
#+begin_src emacs-lisp 
(setq scroll-up-aggressively nil
      scroll-down-aggressively nil
      scroll-preserve-screen-position t)

#+end_src
*** Scrolling when on fringe

Scolling via mouse wheel / trackpad works great, except if my mouse is on the fringe (which I set to be extra-wide). Let's bind margin scroll events appropriately:

#+name: keybindings-scroll
#+begin_src emacs-lisp 
(global-set-key (kbd "<left-margin><wheel-down>") 'mwheel-scroll)
(global-set-key (kbd "<left-margin><wheel-up>") 'mwheel-scroll)
(global-set-key (kbd "<right-margin><wheel-down>") 'mwheel-scroll)
(global-set-key (kbd "<right-margin><wheel-up>") 'mwheel-scroll)
#+end_src

*** Scroll view without moving cursor

Use =M-n= and =M-p= to scroll the window view up or down... without moving the point.

#+name: keybindings-scroll-view
#+begin_src emacs-lisp 
(global-set-key "\M-n" 'scroll-up-line)
(global-set-key "\M-p" 'scroll-down-line)
#+end_src
*** Selecting and deleting text

When I select text between point and mark, I want to see this selection highlighted with transient-mark mode. I find it difficult to use Emacs effectively without having transient-mark-mode turned on.

Delete-selection-mode is also important to me -- it allows overwriting selected text to work the way I expect.

#+name:cursor-transient
#+begin_src emacs-lisp
(transient-mark-mode t)
(delete-selection-mode t)
#+end_src
*** Rectangle selection

CUA mode has [[https://www.youtube.com/watch?v=k-6BVjlBSVo][a really nice facility for editing rectangular regions]]. 

I dislike using CUA-mode's default keybindings, but I do like the rectangle editing features. So I turn off the CUA-keys, then turn on CUA.

#+name:cursor-transient
#+begin_src emacs-lisp
(setq cua-enable-cua-keys nil)               
(cua-mode t)

#+end_src


*** Multiple cursors

Sometimes editing a rectangular region just isn't enough power. Sometimes I need to perform the same action across several lines of varying length. Or sometimes those lines I need to edit aren't consecutive but scattered throughout the file.

Multiple-cursors solves this problem nicely. [[https://www.youtube.com/watch?v=jNa3axo40qM][Check out this raw power.]]

I set my keybindings for this to ones that are very close to those for expand-region, since I often use them in sequence. Expand-region is C-=, so expand-region + mark-next are just a shift key apart.

#+name: cursor-mc
#+begin_src emacs-lisp
(use-package multiple-cursors
:bind (("C-+" . mc/mark-next-like-this)
       ("C--" . mc/mark-previous-like-this)
       ("C-*" . mc/mark-all-like-this)
#+end_src

And some keybindings for activating multiple-cursors when a region is selected:

#+name: cursor-mc-region
#+begin_src emacs-lisp
       ("C-x a l" . mc/edit-lines)
       ("C-x a e" . mc/edit-ends-of-lines)
       ("C-x a a" . mc/edit-beginnings-of-lines)))

#+end_src

*** Expand-region

Another wonderful extension from Magnar Sveen. 

If your point is on a word, hitting C-= expands the selection to mark the whole word. Hitting C-= again selects any punctuation around the word. Hitting C-= again selects the whole line. 

This feature works nicely with various programming languages as well, allowing you to quickly expand the region to highlight a token, an s-expression, a function, etc.

#+name: cursor-er
#+begin_src emacs-lisp
(use-package expand-region
:bind (("C-=" . er/expand-region)))
#+end_src


** Auto-fill & Word Wrap

By defauly, Emacs doesn't automatically wrap words onto the next line.

There are two options to change this. 

In the first option, setting fill-column defines the column number at which Emacs will auto-insert a linebreak.

In the second option, visual-line-mode, no linebreaks are inserted in your text (it's all actually one line in the text file), but it's visually wrapped onto multiple lines. Cursor movement and end-of-line + beginning-of-line commands work within the wrapped line.

*** Auto-fill-mode

I typically run Emacs.app in full screen, and a 120-character fill-column feels pretty good to me. 

I know an 80-column limit would be more compatible... but it feels cramped. Especially when dealing with creative writing.

#+name: auto-fill-options
#+begin_src emacs-lisp
  ;; auto-fill options 
  (setq fill-column 120)
  (setq default-fill-column 120)
  
#+end_src

*** Use Mac EOL characters

Lines should end in plain old LFs, as god intended.

#+name: UI-mac-settings-eol
#+begin_src emacs-lisp 
(setq eol-mnemonic-mac "(Mac)")

#+end_src

*** Visual-line mode and wrap-to-fill-column

Previously I kept auto-fill-mode turned on. The hard linebreaks didn't bother me, and when diffing files in my git repo of creative writing, I could view changes on individual lines.

However... it's still kind of a pain in the ass.

Visual-line-mode would be a fantastic alternative, and it works great... except that it wraps to the full width of the frame. I usually want to work on shorter lines than that, just for usability's sake.

I've since discovered wrap-to-fill-column-mode, which is packaged with nxhtml-mode. This allows me to use visual-line-mode for word.

#+name: auto-fill-options
#+begin_src emacs-lisp
  ;; wrap-to-fill is only included in nxhtml-mode,
  ;;  so we need packages installed before this works.
  ;; 
  ;;(auto-fill-mode 1)
  ;;(add-hook 'text-mode-hook 'turn-on-auto-fill)
  ;; (wrap-to-fill-column-mode 1)
  ;; (add-hook 'text-mode-hook '(lambda() (wrap-to-fill-column-mode 1)))
  (add-hook 'text-mode-hook 'turn-on-visual-line-mode)
#+end_src
*** bzg's big fringe mode

wrap-to-fill-column is packaged with nxhtml, a bloated package I've always hated and which isn't on MELPA. 

So here's another discovery -- bzg's big fring mode: (not currently being activated or tangled)

#+name: big-fringe-mode
#+begin_example
(defvar bzg-big-fringe-mode nil)
(define-minor-mode bzg-big-fringe-mode
  "Minor mode to use big fringe in the current buffer."
  :init-value nil
  :global t
  :variable bzg-big-fringe-mode
  :group 'editing-basics
  (if (not bzg-big-fringe-mode)
      (set-fringe-style nil)
    (set-fringe-mode
     (/ (- (frame-pixel-width)
           (* 120 (frame-char-width)))
        2))))

;; Now activate this global minor mode
(bzg-big-fringe-mode 1)

;; To activate the fringe by default and deactivate it when windows
;; are split vertically, uncomment this:
(add-hook 'window-configuration-change-hook
          (lambda ()
            (if (delq nil
                      (let ((fw (frame-width)))
                        (mapcar (lambda(w) (< (window-width w) fw))
                                (window-list))))
                (bzg-big-fringe-mode 0)
              (bzg-big-fringe-mode 1))))


;; Get rid of the indicators in the fringe
(mapcar (lambda(fb) (set-fringe-bitmap-face fb 'org-hide))
        fringe-bitmaps)
#+end_example


** Desktop Settings

Emacs Desktop allows you to save your current workspace (frame dimensions, window configuration, open buffers, command and file history, and a bunch of other settings). It's pretty rad.

#+name: desktop-settings
#+begin_src emacs-lisp
  (desktop-save-mode 1)
  (setq desktop-globals-to-save
        (append '((extended-command-history . 30)
                  (file-name-history        . 100)
                  (grep-history             . 30)
                  (compile-history          . 30)
                  (minibuffer-history       . 50)
                  (query-replace-history    . 60)
                  (read-expression-history  . 60)
                  (regexp-history           . 60)
                  (regexp-search-ring       . 20)
                  (search-ring              . 20)
                  (shell-command-history    . 50)
                  tags-file-name
                  register-alist)))

#+end_src


** Window Navigation
*** Move to other window

I'm experimenting with using =M-o= to move between windows. The default =C-x o= keybinding is a bit clunky.

#+name: keybindings-other-window
#+begin_src emacs-lisp 
(global-set-key (kbd "M-o") 'other-window)
#+end_src


*** Winner-mode

I don't use this as much anymore, but winner-mode lets you flip between various window/frame configurations.

#+name: window-winner-mode
#+begin_src emacs-lisp
  (winner-mode 1)

#+end_src
*** Previous buffer when splitting window 

Whenever I split my frame into multiple windows (e.g. with =C-x 2= or =C-x 3=), Emacs will open the current buffer in both windows. This isn't always useful.

Usually what I actually want is to show the previous buffer in that new window. [[http://www.reddit.com/r/emacs/comments/25v0eo/you_emacs_tips_and_tricks/chldury][I stole this nice snippet from /r/emacs user chldury]]:

#+name: window-split
#+begin_src emacs-lisp
  (defun vsplit-last-buffer ()
    (interactive)
    (split-window-vertically)
    (other-window 1 nil)
    (switch-to-next-buffer)
    )
  (defun hsplit-last-buffer ()
    (interactive)
     (split-window-horizontally)
    (other-window 1 nil)
    (switch-to-next-buffer)
    )
  
  (global-set-key (kbd "C-x 2") 'vsplit-last-buffer)
  (global-set-key (kbd "C-x 3") 'hsplit-last-buffer)

#+end_src

*** Zoom between split window and single window

[[http://ignaciopp.wordpress.com/2009/05/23/emacs-manage-windows-split/][This function from Ignacio Paz Posse]] has mostly replace winner-mode for me at this point. 

It allows me to move from a split-window view (e.g. two buffers side by side) and "zoom" into one of those buffers, taking it full-frame... and allows me to quickly "zoom" back to the same split-window view.

#+name: window-zoom
#+begin_src emacs-lisp
  (defun toggle-windows-split()
    "Switch back and forth between one window and whatever split of
  windows we might have in the frame. The idea is to maximize the
  current buffer, while being able to go back to the previous split
  of windows in the frame simply by calling this command again."
    (interactive)
    (if (not(window-minibuffer-p (selected-window)))
        (progn
          (if (< 1 (count-windows))
              (progn
                (window-configuration-to-register ?u)
                (delete-other-windows))
            (jump-to-register ?u)))))
  
  (define-key global-map (kbd "C-`") 'toggle-windows-split)
  (define-key global-map (kbd "C-~") 'toggle-windows-split)

#+end_src

*** Shift between windows

Some convenience functions, also stolen from Ignacio Paz Posse.

First we define an "other-window-backward" function that acts just like =C-x-o= but cycles through windows in reverse:

#+name: other-window-backward
#+begin_src emacs-lisp
  (defun other-window-backward (&optional n)
    "Select previous Nth window."
    (interactive "P")
    (other-window (- (prefix-numeric-value n))))

#+end_src   

And now we bind these to some familiar keybindings -- =C-<tab>= and =C-S-<tab>= to cycle backward and foward through windows, and also [prior] and [next] keys.

#+name: window-move-bindings
#+begin_src emacs-lisp
  (global-set-key [prior] 'other-window)
  (global-set-key [next] 'other-window-backward)
  (global-set-key [(control tab)] 'other-window)
  (global-set-key [(shift control tab)] 'other-window-backward)

#+end_src
*** TODO note that C-<tab> doesn't work in org-mode because of binding conflict
*** Shrink/expand windows

Sometimes I want to adjust the size of a window in my split-frame configuration. For example, I may not want my split at 50%, I may want 75% of my frame filled with a view into my source code and 25% showing a REPL. 

I can use the mouse to drag the window boundaries, sure... but it's sometimes faster to do it with my hands on the keyboard:
 
#+name: window-shifting
#+begin_src emacs-lisp
  (define-key global-map (kbd "C-M-<left>") 'shrink-window-horizontally)
  (define-key global-map (kbd "C-M-<right>") 'enlarge-window-horizontally)
  (define-key global-map (kbd "C-M-<up>") 'enlarge-window)
  (define-key global-map (kbd "C-M-<down>") 'shrink-window)

#+end_src  

** File & Buffer Navigation & Manipulation
*** Buffer lists

I really like ibuffer for listing all open buffers. I've bound it to =C-x C-b=. 

#+name: ibuffer
#+begin_src emacs-lisp
(global-set-key "\C-x\C-b" 'ibuffer)

#+end_src
*** Edit filenames in dired
Dired is awesome for viewing and manipulating files in a directory. Wdired makes it even more awesome -- it lets you edit filenames in a dired buffer (editing them just like any text file), then save your changes to bulk-rename files and more.

I like having wdired bound to the 'r' key inside dired.

(note that I'm eval-ing this only after loading dired, otherwise Emacs chokes on an undefined dired-mode-map var)

#+name: wdired
#+begin_src emacs-lisp
(eval-after-load 'dired
  '(define-key dired-mode-map "r"
     'wdired-change-to-wdired-mode))

#+end_src
*** Make =C-<= and =C->= work nicely in dired-mode

Thanks to Magnar Sveen for this one. This snippet makes =C-<= and =C->= send the cursor to the beginning/end of the filenames in dired buffers. Handy!

#+name: dired-c-a
#+begin_src emacs-lisp
  (defun dired-back-to-top ()
    (interactive)
    (beginning-of-buffer)
    (dired-next-line 4))
  
  (eval-after-load 'dired
    '(define-key dired-mode-map
      (vector 'remap 'beginning-of-buffer) 'dired-back-to-top))
  
  (defun dired-jump-to-bottom ()
    (interactive)
    (end-of-buffer)
    (dired-next-line -1))
  
  (eval-after-load 'dired
    '(define-key dired-mode-map
      (vector 'remap 'end-of-buffer) 'dired-jump-to-bottom))

#+end_src

*** Auto-revert dired

This code is supposed to auto-revert (refresh) dired buffers when things change, but I don't think it works the way I want it to work:

#+name: auto-revert-dired
#+begin_src emacs-lisp
  (setq global-auto-revert-non-file-buffers t)
  (setq auto-revert-verbose nil)

#+end_src
*** Rename and delete files

Renaming and deleting files should be easier to do while you're viewing them.

Since =C-x k= kills a buffer, it makes sense to bind =C-x C-k= to deleting the current file (with confirmation, of course).

And =C-x C-w= is bound to write-file... but a more useful feature would be to simple rename the current buffer and file. This is bound to =C-x C-r=.

#+name: rename-and-delete-files
#+begin_src emacs-lisp  
  (defun rename-current-buffer-file ()
    "Renames current buffer and file it is visiting."
    (interactive)
    (let ((name (buffer-name))
          (filename (buffer-file-name)))
      (if (not (and filename (file-exists-p filename)))
          (error "Buffer '%s' is not visiting a file!" name)
        (let ((new-name (read-file-name "New name: " filename)))
          (if (get-buffer new-name)
              (error "A buffer named '%s' already exists!" new-name)
            (rename-file filename new-name 1)
            (rename-buffer new-name)
            (set-visited-file-name new-name)
            (set-buffer-modified-p nil)
            (message "File '%s' successfully renamed to '%s'"
                     name (file-name-nondirectory new-name)))))))
  
  (global-set-key (kbd "C-x C-r") 'rename-current-buffer-file)
  
  
  (defun delete-current-buffer-file ()
    "Removes file connected to current buffer and kills buffer."
    (interactive)
    (let ((filename (buffer-file-name))
          (buffer (current-buffer))
          (name (buffer-name)))
      (if (not (and filename (file-exists-p filename)))
          (ido-kill-buffer)
        (when (yes-or-no-p "Are you sure you want to remove this file? ")
          (delete-file filename t)
          (kill-buffer buffer)
          (message "File '%s' successfully removed" filename)))))
  
  (global-set-key (kbd "C-x C-k") 'delete-current-buffer-file)
  #+end_src
*** Drag and drop file support

When I drag and drop a file onto Emacs.app, visit that file rather than just appending it to the currently open buffer (which is a horrible default).

#+name: Filenav-drag-n-drop
#+begin_src emacs-lisp 

(define-key global-map [ns-drag-file] 'ns-find-file) 

#+end_src
*** Make M-x locate use OS X's Spotlight

Leverage OS X's mdfind util for crazy-fast file locating. Try it with =M-x locate=.

#+name: locate-spotlight
#+begin_src emacs-lisp
  (setq locate-make-command-line (lambda (s) `("mdfind" "-name" ,s)))

#+end_src
*** Re-open file as root

[[http://t.co/KiAWcJoo][Thanks to @christopherdone for this one]].

#+name: open-as-root
#+begin_src emacs-lisp
  (defun tramp-sudo-reopen ()
    "Re-open the current with tramp."
    (interactive)
    (let ((file-name (format "/sudo:localhost:%s" (buffer-file-name)))
          (line (line-number-at-pos))
          (column (current-column)))
      (kill-buffer)
      (find-file file-name)
      (goto-line line)
      (goto-char (+ (point) column))))

#+end_src
*** isearch using token at point

#+name: isearch-token
#+begin_src emacs-lisp
  ;;-----------------------------------------------------------------------------
  ;; Nice functions to change copy-kill region to copy or kill current line
  ;; if no active region.
  ;; Stolen from http://xahlee.org/emacs/emacs_copy_cut_current_line.html
  ;;-----------------------------------------------------------------------------
  (defadvice kill-ring-save (before slick-copy activate compile)
    "When called interactively with no active region, copy the current line."
    (interactive
     (if mark-active
         (list (region-beginning) (region-end))
       (progn
         (message "Current line copied to kill-ring.")
         (list (line-beginning-position) (line-beginning-position 2)) ) ) ))
  
  (defadvice kill-region (before slick-copy activate compile)
    "When called interactively with no active region, cut the current line."
    (interactive
     (if mark-active
         (list (region-beginning) (region-end))
       (progn
         (list (line-beginning-position) (line-beginning-position 2)) ) ) ))

   #+end_src
*** TODO finish documenting this
*** ace-jump mode

Handy for very fast navigation around a file.

#+name: ace-jump
#+begin_src emacs-lisp
  (use-package ace-jump-mode
               :bind ("C-." . ace-jump-mode))
#+end_src
*** TODO document ace-jump-mode usage more
** Copy & Kill
*** Use Mac clipboard for copying/killing

Copy and paste should use the OS clipboard

#+name: UI-mac-settings-clipboard
#+begin_src emacs-lisp 
(setq x-select-enable-clipboard t)
#+end_src


** Emacsclient / Server

My preferred way of working is in a single fullscreen frame in Emacs.app that's open all the time, running as a server. 

If I'm working in the terminal and I need to edit a file in my current directory, I can just do:

#+begin_example 
$> emacsclient filename.txt
#+end_example

This will open filename.txt within my already-running Emacs.app instance. Sweet.[fn:3]

*** Connecting to Emacs server shouldn't pop up frames


One thing I had to tweak for this: I want to make sure connecting via emacsclient doesn't spawn a new frame for editing -- I want to use the existing frame.

#+name: UI-pop-up-frames
#+begin_src emacs-lisp 
(setq ns-pop-up-frames nil)

#+end_src

[fn:3] I actually aliased emacsclient to =em= in bash to make this even simpler. =$>em filename.txt= drops me into my existing already-running Emacs session and visits the file.

-------------------------------------

** ido & smex
** Help
* Writing Fiction
* Coding
** Return + indent

I like it when my return key preserves indentation:

#+name: keybindings-return
#+begin_src emacs-lisp
(global-set-key (kbd "RET") 'newline-and-indent)

#+end_src

** Bind ESC to top-level command 

I hate having to repeatedly hit escape to bounce out of recursive edits when I drop into the debugger.  

#+name: keybindings-escape
#+begin_src emacs-lisp
(global-set-key (kbd "<C-escape>") 'top-level)  
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(add-hook 'org-mode-hook
          (lambda()
            (define-key org-mode-map (kbd "<escape>") 'keyboard-escape-quit)))

#+end_src

* Org-mode
* Global Keybindings
:PROPERTIES:
:noweb-ref: Set custom keybindings
:END:

* Editor customizations
:PROPERTIES:
:noweb-ref: Load some editor customizations
:END:

#+name: editor-settings
#+begin_src emacs-lisp 
  ;;-----------------------------------------------------------------------------
  ;; System / Editing Prefs
  ;;-----------------------------------------------------------------------------
  
    
  ;; Refresh any buffer when file on disk changes
  (setq global-auto-revert-mode 1)
  
  
  ;; ...Also rebuild Tags files, and be quiet about it
  (setq tags-revert-without-query t)
  
  ;; M-x locate uses OS X's Spotlight
  (setq locate-make-command-line (lambda (s) `("mdfind" "-name" ,s)))
  
  
  ;; Tabs insert 4 spaces, sentences have one space (as God intended).
  (setq-default tab-width 4)
  (setq-default indent-tabs-mode nil)
  (setq sentence-end-double-space nil)
  
  
   
  ;; Bookmark options
  (setq bookmark-default-file (concat dotemacs-dir "bookmarks"))
  
  ;; spellcheck options
  (setq ispell-program-name "aspell")
  
  ;; Tramp defaults
  (setq tramp-default-method "ssh")
  
  ;; Make sure diff works with .org files and others
  (setq diff-switches "-a -c")
  
  ;; Let me upcase/downcase regions
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
  
  ;; ignore case when completing, including filenames
  (setq completion-ignore-case t           
    read-file-name-completion-ignore-case t)
  
  ;; Let me narrow to region -- I use this a bunch
  (put 'narrow-to-region 'disabled nil)
  
  
  
#+end_src


* System and editor settings
* Load and configure packages
:PROPERTIES:
:noweb-ref: Load and configure packages
:CUSTOM_ID: load-packages
:END:
Here's the good stuff!

** Set package sources
I want to add a few other sources (notably marmalade and melpa) to my package source list
  
#+name: packages-set-sources
#+begin_src emacs-lisp
(require 'package)
(dolist (source '( ("gnu" . "http://elpa.gnu.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("melpa" . "http://melpa.milkbox.net/packages/")))
  (add-to-list 'package-archives source t))
(package-initialize)
#+end_src

** Add ELPA and el-get package directories to load path  

#+name: packages-add-to-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path (concat dotemacs-dir "elpa"))
;; (add-to-list 'load-path (concat dotemacs-dir "el-get/el-get"))
#+end_src

 
** Bootstrap el-get

#+name: packages-el-get-bootstrap
#+begin_src emacs-lisp
  ;; el-get, install thyself!
  ;; (unless (require 'el-get nil t)
  ;;  (url-retrieve
  ;;   "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
  ;;   (lambda (s)
  ;;     (let ((el-get-master-branch) (el-get-install-skip-emacswiki-recipes))
  ;;       (goto-char (point-max))
  ;;       (eval-print-last-sexp)))))
#+end_src

And set some directory vars

#+name: packages-set-el-get-dirs
#+begin_src emacs-lisp
  ;; (setq el-get-dir (concat dotemacs-dir "el-get")
  ;;       el-get-user-package-directory (concat dotemacs-dir "config"))
#+end_src


 
** Load packages
#+name: init-packages
#+begin_src emacs-lisp
  ;; (require 'init-packages)
#+end_src

* Custom functions and tweaks
:PROPERTIES:
:noweb-ref: Load a bunch of custom functions
:CUSTOM_ID: custom-functions
:END:

#+name: init-packages
#+begin_src emacs-lisp
  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;
  ;; A random smattering of custom/helper functions
  ;;
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  
  
  ;;-----------------------------------------------------------------------------
  ;; jcs:getcals -- Sync my Google Calendars to emacs diary
  ;;-----------------------------------------------------------------------------
  (require 'icalendar)
  
  (defun getcal (url)
    "Download ics file and add to diary"
    (let ((tmpfile (url-file-local-copy url)))
      (icalendar-import-file tmpfile "~/org/calendar.diary" t)
      (kill-buffer (car (last (split-string tmpfile "/"))))
      )
    )
  
  ;; Grab google calendars from secrets.el.gpg
  (defun jcs:getcals ()
    (interactive)
    (if (not (boundp 'google-calendars))
        (jcs:decrypt-secrets))
      (find-file "~/org/calendar.diary")
      (flush-lines "^[& ]")
      (dolist (url google-calendars) (getcal url))
      (kill-buffer "calendar.diary"))
  
  
  ;;-----------------------------------------------------------------------------
  ;; jcs:clock functions -- Functions to clock into/out of  a particular item in
  ;; projects.org (OR create a new item and clock into it)
  ;;-----------------------------------------------------------------------------
   (defun jcs:clock-in-to-string (theString &optional theCategory)
    "Clock into a particular item in ~/org/projects.org file. Takes optional Category param."
    (interactive)
    (save-excursion
      (let (filepath filename mybuffer)
        (setq filepath "/Users/jstautz/org/projects.org"
              filename (file-name-nondirectory filepath)
              mybuffer (find-file filepath))
        (goto-char (point-min))
        (widen) 
        ;; if no category defined, try to find string in file and clock in
        (if (eq theCategory nil)
            (if (search-forward theString nil t)
                (org-clock-in)
              ;; if not found in buffer, insert new item at end and clock into it
              (goto-char (point-max))
              (insert (concat "*** " theString))
              (goto-char (point-max))
              (org-clock-in))
          ;; thecategory is non-nil, so this is a new item w/ category
          (goto-char (point-max))
          (insert (concat "*** " theString "\n  :PROPERTIES:\n  :CATEGORY: " theCategory "\n  :END:\n"))
          (goto-char (point-max))
          (org-clock-in)))))
  
  (defun jcs:clock-out (&optional theString theCategory)
    (org-clock-out))
  
  
  ;;-----------------------------------------------------------------------------
  ;; Eval and replace -- replace current sexp with its value
  ;;-----------------------------------------------------------------------------
  
  (defun eval-and-replace ()
    "Replace the preceding sexp with its value."
    (interactive)
    (backward-kill-sexp)
    (prin1 (eval (read (current-kill 0)))
           (current-buffer)))
  
  (global-set-key (kbd "C-c e") 'eval-and-replace)
  
  
  
  ;;-----------------------------------------------------------------------------
  ;; Make zap-to-char act more like "zap-up-to-char"
  ;; Thanks to Eric Himmelreich
  ;; http://rawsyntax.com/blog/learn-emacs-use-defadvice-modify-functions/
  ;;-----------------------------------------------------------------------------
  (defadvice zap-to-char (after my-zap-to-char-advice (arg char) activate)
    "Kill up to the ARG'th occurence of CHAR, and leave CHAR.
    The CHAR is replaced and the point is put before CHAR."
    (insert char)
    (forward-char -1))
  
  
  
  ;;-----------------------------------------------------------------------------
  ;; Open in Marked.app -- Stolen from https://github.com/mattsears/emacs
  ;;-----------------------------------------------------------------------------
  (defun markdown-preview-file ()
    "run Marked on the current file and revert the buffer"
    (interactive)
    (shell-command
     (format "open -a /Applications/Marked.app %s"
             (shell-quote-argument (buffer-file-name)))))
  
  (global-set-key "\C-cm" 'markdown-preview-file)
  
  
  ;;-----------------------------------------------------------------------------
  ;; Unfill paragraph -- From https://raw.github.com/qdot/conf_emacs/master/emacs_conf.org
  ;;-----------------------------------------------------------------------------
  (defun unfill-paragraph ()
    "Takes a multi-line paragraph and makes it into a single line of text."
    (interactive)
    (let ((fill-column (point-max)))
      (fill-paragraph nil)))
  
  
  
  ;;-----------------------------------------------------------------------------
  ;; auto-recompile elisp -- Thanks to Adolfo Benedetti and Xah Lee
  ;;-----------------------------------------------------------------------------
  (defun byte-compile-current-buffer ()
    "`byte-compile' current buffer if it's emacs-lisp-mode and compiled file exists."
    (interactive)
    (when (and (eq major-mode 'emacs-lisp-mode)
               (file-exists-p (byte-compile-dest-file buffer-file-name)))
      (byte-compile-file buffer-file-name)))
  
  (add-hook 'after-save-hook 'byte-compile-current-buffer)
  
  
  ;;-----------------------------------------------------------------------------
  ;; A smarter find-tag that automagically reruns etags when it can't find a
  ;; requested item and then makes a new try to locate it.
  ;; by Jonas.Jarnestrom<at>ki.ericsson.se
  ;; Fri Mar 15 09:52:14 2002
  ;;-----------------------------------------------------------------------------
  (defadvice find-tag (around refresh-etags activate)
    "Rerun etags and reload tags if tag not found and redo find-tag.
     If buffer is modified, ask about save before running etags."
    (let ((extension (file-name-extension (buffer-file-name))))
      (condition-case err
          ad-do-it
        (error (and (buffer-modified-p)
                    (not (ding))
                    (y-or-n-p "Buffer is modified, save it? ")
                    (save-buffer))
               (er-refresh-etags extension)
               ad-do-it))))
  
  (defun er-refresh-etags (&optional extension)
    "Run etags on all peer files in current dir and reload them silently."
    (interactive)
    (shell-command (format "etags *.%s" (or extension "el")))
    (let ((tags-revert-without-query t))  ; don't query, revert silently
      (visit-tags-table default-directory nil)))
  
  ;; While we're at it, modify pop-tag-mark to stay centered on cursor
  (defadvice pop-tag-mark (after my-pop-tag-mark-advice activate)
    "After popping back to where find-tag was invoked,
     center screen on cursor"
    (let ((current-prefix-arg '(4)))
    (call-interactively 'recenter-top-bottom)))
  
  
#+end_src
* Other Implementation details

This section contains some less-interesting details that I won't be modifying all that often, but were still important to document. 

** Prerequisites and setup
:PROPERTIES:
:noweb-ref: Prerequisites and setup -- load basic support libraries, set some useful variables
:CUSTOM_ID: setup
:END:  

This section contains the first bits of elisp in my config that get loaded. 

*** First, let's load common lisp libraries

This is generally a good idea.

#+name: setup-require-cl :comments both
#+begin_src emacs-lisp
(require 'cl)

#+end_src

*** Then set our path appropriately.

This is kind of a gross hack to grab the $PATH environment variable from my ~/.bashrc and use this. This way my path is consistent between Emacs and my shell elsewhere.

#+name: setup-path :comments both
#+begin_src emacs-lisp
(let ((jcs:shell-path (shell-command-to-string ". ~/.bashrc; echo -n $PATH")))
  (setenv "PATH" jcs:shell-path)
  (setq exec-path (split-string jcs:shell-path ":")))

#+end_src
 
*** Set a few variables for directories

Define our home directory, dot emacs directory (where the config lives), emacs binary directory (where Emacs.app lives), and info file directory.

I use these =*-dir= variables all over the place in my config.

#+name: setup-dirs :comments both
#+begin_src emacs-lisp
(setq home-dir "/Users/jstautz/"
      dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name)))
      emacs-dir "/Applications/Emacs.app/Contents/"
      emacs-bin (concat emacs-dir "MacOS/Emacs")
      info-dir (concat emacs-dir "Resources/info/"))
#+end_src

*** Add .emacs.d to load-path

...Kinda necessary.

#+name: setup-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path dotemacs-dir)
#+end_src
*** Tell 'customize' where to save changes

Emacs has a neat customize feature, accessible via =M-x customize=, which lets you modify user-configurable variables in a simpler (read: non-elisp) interface.

I don't generally use it -- I prefer to =setq= these variables in my init files manually -- but sometimes I'll fiddle with settings in customize to try things out.

When I do so, I'd like customize to save things in a separate =emcas-custom= file. I treat this file as temporary storage. If I like the changes, I'll pull them out of this file and place them in the appropriate places in my config.

#+name: setup-custom-file
#+begin_src emacs-lisp
(setq custom-file (concat dotemacs-dir "emacs-custom.el"))

#+end_src

*** Set garbage collection threshold higher

Props to Le Wang for this one.

[[https://github.com/lewang/flx][According to his documentation in flx]], Emacs will start GC every 0.76MB allocated, which is way too often on modern machines. We want to boost that to 20MB:

#+name: setup-gc-settings
#+begin_src emacs-lisp
(setq gc-cons-threshold 20000000)

#+end_src

*** Finally, decrypt secrets.el.gpg

Passwords, private URLs, and personal info are encrypted and stored in the secrets.el.gpg file. Emacs decrypts this using the keys in my .gnupg keyring.

I do this *before* I begin loading packages so that package configs can access variables stored in the secrets file.

#+name: setup-decrypt-secrets-function
#+begin_src emacs-lisp
(defun jcs:decrypt-secrets ()
  (interactive)
  (require 'secrets))

#+end_src


** Post-flight -- final steps
:PROPERTIES:
:noweb-ref: Post-flight: load Emacs desktop and start server
:CUSTOM_ID: final-steps
:END:

These are the final bits of code that get run in my config.

*** Restore my desktop

(I'm not sure why this is required now when it wasn't before -- something slightly different after changing my config.)

#+name: desktop-read
#+begin_src emacs-lisp
(desktop-read)
#+end_src

*** Start server

Now that everything's good to go, start the emacs server so we can connect to it using =emacsclient= from the command line.

#+name: server-start
#+begin_src emacs-lisp
(server-start)
#+end_src
