#+TITLE: jstautz's Emacs config
#+OPTIONS: toc:nil num:nil ^:nil

#+begin_quote
People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen -- the editor should get used to us.

-- [[http://blog.vivekhaldar.com/post/31970017734/new-frontiers-in-text-editing][Vivek Hadlar]]
#+end_quote


#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

** What is this?
:PROPERTIES:
:CUSTOM_ID: what_is_this
:END:

A [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] version of my Emacs config files.

My current setup borrows liberally from Emacs users far smarter than I am, including:
- [[http://doc.norang.ca/org-mode.html][Bernt Hansen]] 
- [[https://github.com/eschulte/emacs24-starter-kit][Eric Schulte]]
- [[https://github.com/magnars/.emacs.d][Magnar Sveen]]
- [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua]]
- [[https://github.com/technomancy/dotfiles][Phil Hagelberg]]
- [[https://github.com/bodil/emacs.d][Bodil Stokke]]
- [[http://www.masteringemacs.org/][Mickey Petersen]]
- And a ton of others. 

Props and thank-yous and praises are scattered through my config in places where I can remember who I stole something from.

** What the hell is literate programming?
:PROPERTIES:
:CUSTOM_ID: what_is_literate
:END: 

Short answer: instead of writing separate documentation, the documentation /contains/ the program. 

Or as Knuth puts it:

#+begin_quote 
I believe that the time is ripe for significantly better documentation of programs, and that we can best achieve this by considering programs to be works of literature. Hence, my title: "Literate Programming."

Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to humans what we want the computer to do.

 Donald E. Knuth, Literate Programming, 1984
#+end_quote

Okay, so Knuth takes it to a bit of an extreme. I've got an MFA in creative writing, and even /I/ think that "considering progams to be works of literature" is nutso. 

But improving documentation in a way that makes it easier for humans to understand? Hell yeah, let's do it.

** Disclaimers and Warnings
:PROPERTIES:
:CUSTOM_ID: disclaimer
:END:

You /don't/ want to try and use my configs straight out of the box. 

- This is a perpetual work in progress. 
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies, and there are probably a bunch of undocumented dependencies.
- Requires Emacs 24.3. Only tested on Mac OS X.
- First load will require an internet connection to download packages (this will take a while).
- I'm not responsible if any of this blows up on you (see [[License]] below).

** Why use literate programming for my Emacs config?
:PROPERTIES:
:CUSTOM_ID: why-literate
:END:

It's an experiment. We'll see how well it works out.

I've been inspired by [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua's literate emacs config]], as well as by [[http://doc.norang.ca/org-mode.html][Bernt Hansen's amazingly thorough and detailed documentation of his org-mode setup]].

I've also read some pretty stunning documentation in the Javascript world that is pretty "literate," even if it doesn't fully conform to Knuth's ideals. Good examples are [[http://jashkenas.github.io/coffee-script/documentation/docs/grammar.html][Coffeescript]] and [[http://underscorejs.org/docs/underscore.html][Underscore.js]].

Using a literate programming approach using org-babel has a number of advantages that appeal to me:

1. *Better organization of my .emacs lisp files*
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure.
   - I'm able to add headers and subsections to better organize my code -- way better than using giant banner-style comment blocks.
   - My configuration is easier to read and understand. It also looks good on github!
2. *I'm better able to follow my own thought processes.*
   - Code is organized according to how I think, not how the interpreter thinks -- I can explain code snippets in an order that makes sense to me, and org-babel later compiles these into the correct order.
   - Explanations take priority, code is secondary.
   - When I revisit code I wrote ten years ago, I have a hope of understanding not just what it does, but /what the hell I was thinking./
3. *Sharing my setup is easier*
   - Org-mode's publishing features mean that it's pretty simple to export my documentation and publish it.
   - I have one file that generates nice-looking documentation and the code itself.
   - Better, more detailed explanations of my code mean it's easier for others to understand it and benefit from it.






My emacs config has gone through a couple of iterations over the years. I started learning Emacs in 2000 while I was taking CS courses in school. My first Emacs config was pretty simplistic:

*Single-file + manually-installed packages*
   - A giant .emacs file
   - badly-organized
   - badly-commented
   - full of a mishmash of elisp scraps collected from the interwebs
   - 3rd party packages were manually installed -- everything lived together in a jumble

After Emacs 24 came out, I started playing around with the built-in package manager. It's amazing. But then I made an even more amazing discovery: el-get.

I then reworked my config pretty extensively around el-get:

*Multiple files + el-get packages*
   - Split my config into separate files for basic setup, loading packages, custom functions, etc.
   - Using el-get to download, install, manage packages
   - configs for each package contained in /config directory









** License
:PROPERTIES:
:CUSTOM_ID: license
:END:
#+begin_example
Copyright (C)  2014  Jeff Stautz

Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts.
  
Code in this document is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.
  
This code is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
#+end_example 

This document (including HTML format or raw org-mode format) is licensed under the GNU Free Documentation License version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

The code examples and CSS stylesheets are licensed under the GNU General Public License v3 or later (http://www.gnu.org/licenses/gpl.html).

*** Structure 
   :PROPERTIES:
   :CUSTOM_ID: structure
   :END:
The =init.el= file is loaded automatically by Emacs on startup. It fires up org-mode and then loads the elisp snippets embedded in this emacs-init.org file.

Packages are loaded using el-get. Configurations for each package live in the /config/init-package-name.el files -- each of these loads the corresponding package-config.org file to configure the package.



**** .emacs.d directory structure




**** how things get loaded
**** 

* Implementation  
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:

*** Prerequisites and setup  
***** First, load common lisp libraries

#+name: setup-require-cl
#+begin_src emacs-lisp
(require 'cl)
#+end_src

*** Then set our path appropriately.

I use a somewhat gross hack to grab the $PATH environment variable from my ~/.bashrc and use this. This way my path is consistent between Emacs and my shell elsewhere.

#+name: setup-path :comments both
#+begin_src emacs-lisp
  (let ((jcs:shell-path (shell-command-to-string ". ~/.bashrc; echo -n $PATH")))
    (setenv "PATH" jcs:shell-path)
    (setq exec-path (split-string jcs:shell-path ":")))
#+end_src


******* TODO replace the above with $PATH? 
***** Set a few variables for directories

Define our home directory, dot emacs directory (where the config lives), emacs binary directory (where Emacs.app lives), and
info file directory.

I use these =*-dir= variables all over the place in my config.

#+name: setup-dirs
#+begin_src emacs-lisp
(setq home-dir "/Users/jstautz/"
      dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name)))
      emacs-dir "/Applications/Emacs.app/Contents/"
      emacs-bin (concat emacs-dir "MacOS/Emacs")
      info-dir (concat emacs-dir "Resources/info/"))
#+end_src

***** Tell 'customize' where to save changes

Emacs has a neat customize feature, accessible via =M-x customize=, which lets you modify user-configurable variables in
a simpler (read: non-elisp) interface.

I don't generally use it -- I prefer to =setq= these variables in my init files manually -- but sometimes I'll fiddle
with settings in customize to try things out.

When I do so, I'd like customize to save things at the bottom of my init-customizations.el file. If I like the changes,
I'll pull them out of the customize section of this file and place them in the appropriate places in my config.

#+name: setup-custom-file
#+begin_src emacs-lisp
(setq custom-file (concat dotemacs-dir "init-customizations.el"))
#+end_src

******* TODO depending on how I change the file structure, I may aim this at a different file

***** Add .emacs.d to load-path

#+name: setup-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path dotemacs-dir)
#+end_src

***** Finally, decrypt secrets.el.gpg

Passwords, private URLs, and personal info are encrypted and stored in the secrets.el.gpg file. Emacs decrypts this
using the keys in my .gnupg keyring.

I do this before I begin loading packages so that package configs can access variables stored in the secrets file.

#+name: setup-decrypt-secrets-function
#+begin_src emacs-lisp
(defun jcs:decrypt-secrets ()
  (interactive)
  (require 'secrets))
#+end_src

*** Keybindings
*** Sync and load packages

Here's the good stuff!

***** Set package sources
I want to add a few other sources (notably marmalade and melpa) to my package source list
  
#+name: packages-set-sources
#+begin_src emacs-lisp
(require 'package)
(dolist (source '( ("gnu" . "http://elpa.gnu.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("melpa" . "http://melpa.milkbox.net/packages/")))
  (add-to-list 'package-archives source t))
(package-initialize)
#+end_src

***** Add ELPA and el-get package directories to load path  

#+name: packages-add-to-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path (concat dotemacs-dir "elpa"))
(add-to-list 'load-path (concat dotemacs-dir "el-get/el-get"))
#+end_src

 
***** Bootstrap el-get

#+name: packages-el-get-bootstrap
#+begin_src emacs-lisp
;; el-get, install thyself!
(unless (require 'el-get nil t)
 (url-retrieve
  "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
  (lambda (s)
    (let ((el-get-master-branch) (el-get-install-skip-emacswiki-recipes))
      (goto-char (point-max))
      (eval-print-last-sexp)))))
#+end_src

And set some directory vars

#+name: packages-set-el-get-dirs
#+begin_src emacs-lisp
(setq el-get-dir (concat dotemacs-dir "el-get")
      el-get-user-package-directory (concat dotemacs-dir "config"))
#+end_src


 
***** Load packages
#+name: init-packages
#+begin_src emacs-lisp
(require 'init-packages)
#+end_src

*** Customizations

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-customizations)
#+end_src

*** Custom functions and tweaks

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-custom-functions)
#+end_src
*** Final steps

***** Restore my desktop

I'm not sure why this is required now when it wasn't before -- something slightly different after changing my config.

#+name: desktop-read
#+begin_src emacs-lisp
(desktop-read)
#+end_src


***** start server
Now that everything's good to go, start the emacs server so we can connect to it using =emacsclient= from the command line

#+name: server-start
#+begin_src emacs-lisp
(server-start)
#+end_src
* Scraps 





ideas stolen from various places around the internet, hundreds of tiny tweaks and fiddles, and a few hand-written hunks of elisp of which I am not entirely proud.
With special thanks to


I've recently reworked my .emacs files to follow a [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] paradigm. 

Org-mode files (such as this one) provide the explanations, notes, and thought processes behind my configuration.

The emacs lisp code blocks embedded within these org-mode files are loaded to perform the actual configuration.

The advantages to this approach are:

1. Better organization of my .emacs lisp files
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure
   - I'm able to add headers and subsections to better organize my code
   - My configuration is easier to read and understand -- it also looks good on github!

2. I'm better able to follow my own thought processes
   - Code is organized according to how I think, not how the interpreter thinks
   - Explanations take priority, code is secondary
   - Documentation can be more thorough than regular code comments
