#+TITLE: Jeff's Emacs config
#+OPTIONS: toc:nil num:t ^:nil

#+begin_quote
People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen -- the editor should get used to us.

-- [[http://blog.vivekhaldar.com/post/31970017734/new-frontiers-in-text-editing][Vivek Hadlar]]
#+end_quote


#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

** What is this?
:PROPERTIES:
:CUSTOM_ID: what_is_this
:END:

It's a [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] version of my Emacs config files.

My current setup borrows liberally from Emacs users far smarter than I am, including:
- [[http://doc.norang.ca/org-mode.html][Bernt Hansen]] 
- [[https://github.com/eschulte/emacs24-starter-kit][Eric Schulte]]
- [[https://github.com/magnars/.emacs.d][Magnar Sveen]]
- [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua]]
- [[https://github.com/technomancy/dotfiles][Phil Hagelberg]]
- [[https://github.com/bodil/emacs.d][Bodil Stokke]]
- [[http://www.masteringemacs.org/][Mickey Petersen]]
- And a ton of others. 

Props and praises are scattered throughout my config in places where I can remember who I stole something from.

** Disclaimers and Warnings
:PROPERTIES:
:CUSTOM_ID: disclaimer
:END:

You /don't/ want to try and use my configs straight out of the box. 

- This is a perpetual work in progress. 
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies, and there are probably a bunch of undocumented dependencies.
- Requires Emacs 24.3. Only tested on Mac OS X.
- First load will require an internet connection to download packages (this will take a while).
- I'm not responsible if any of this blows up on you.

** What the hell is literate programming?
:PROPERTIES:
:CUSTOM_ID: what_is_literate
:END: 

Short answer: instead of writing separate documentation, the documentation /contains/ the program. 

Or as Knuth puts it:

#+begin_quote 
I believe that the time is ripe for significantly better documentation of programs, and that we can best achieve this by considering programs to be works of literature. Hence, my title: "Literate Programming."

Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to humans what we want the computer to do.

—Donald E. Knuth, Literate Programming, 1984
#+end_quote

The document you're reading now is an org-mode text file that contains both code and documentation. 

On startup, emacs pulls out ("tangles") the code snippets in this file and uses them to configure the editor.

** Why use literate programming for my Emacs config?
:PROPERTIES:
:CUSTOM_ID: why-literate
:END:

It's an experiment. We'll see how well it works out.

I've been inspired by [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua's literate emacs config]], as well as by [[http://doc.norang.ca/org-mode.html][Bernt Hansen's amazingly thorough and detailed documentation of his org-mode setup]].

I've also read some stunning documentation in the Javascript world that is pretty "literate," even if it doesn't fully conform to Knuth's ideals. Good examples are [[http://jashkenas.github.io/coffee-script/documentation/docs/grammar.html][Coffeescript]] and [[http://underscorejs.org/docs/underscore.html][Underscore.js]].

Using a literate programming approach using org-babel has a number of advantages that appeal to me:

1. *Better organization of my .emacs lisp files*
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure.
   - I'm able to add headers and subsections to better organize my code -- way better than using giant banner-style comment blocks.
   - My configuration is easier to read and understand. It also looks good on github!
2. *I'm better able to follow my own thought processes.*
   - Code is organized according to how I think, not how the interpreter thinks -- I can explain code snippets in an order that makes sense to me, and org-babel later compiles these into the correct order.
   - Explanations take priority, code is secondary.
   - When I revisit code I wrote ten years ago, I have a hope of understanding not just what it does, but /what the hell I was thinking./
3. *Sharing my setup is easier*
   - Org-mode's publishing features mean that it's pretty simple to export my documentation and publish it.
   - I have one file that generates nice-looking documentation and the code itself.
   - Better, more detailed explanations of my code mean it's easier for others to understand it and benefit from it.

** License
:PROPERTIES:
:CUSTOM_ID: license
:END:

I don't actually need a license for this, but I feel /way/ cooler having one here.

#+begin_example
Copyright (C)  2014  Jeff Stautz

Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts.
  
Code in this document is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.
  
This code is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
#+end_example 

This document (including HTML format or raw org-mode format) is licensed under the GNU Free Documentation License version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

The code examples and CSS stylesheets are licensed under the GNU General Public License v3 or later (http://www.gnu.org/licenses/gpl.html).

* What I use Emacs for
:PROPERTIES:
:CUSTOM_ID: what-i-do-in-emacs
:END:

#+begin_quote
This is my rifle. There are many like it, but this one is mine.

--Major General William H. Rupertus, "The Rifleman's Creed," 1942
#+end_quote

In order to understand why I've configured things the way I did, it might help to understand some things I do in Emacs.

** Org-mode

I spend 90% of my time in Emacs inside [[http://orgmode.org/][org-mode]]. 

I've been using it for several years for taking notes, planning, writing, and tracking my to-do lists. I've got a [[file:./init-org.org][whole section of my Emacs config dedicated to the ins and outs of my org-mode configuration.]]

It's gnarly. It's complicated. It involves a lot of yak-shaving. It's ripe for refactoring. But it /works/ for me. 

** Writing Fiction

For the last 9 years, I've done most of my writing, editing, and revising in plain text within Emacs.

Instead of using Microsoft Word or Pages, I write in plain text using either:
1. [[https://daringfireball.net/projects/markdown/][Markdown syntax]], viewing the formatted results in [[http://markedapp.com/][Marked.app]]
2. Minimal [[http://www.latex-project.org/][LaTeX markup]], which I then run through a perl script to add full LaTeX document headers.

The details of how I use Emacs for fiction writing are [[file:./emacs-init.org][documented here]]. 

** Programming

Unlike most Emacs users, I don't do a ton of software development in Emacs. I'm not a professional software engineer -- I only dabble, and I only pretend like I know what I'm doing. I work with a ton of talented engineers every day

A couple of languages I use:

- I work with Emacs lisp quite a bit (of course)
- I'm learning python
- I play around with javascript (and HTML/CSS)

My Emacs settings for software dev should be taken with several grains of salt -- these parts of my config aren't very mature and I'm probably doing everything wrong.

** Manipulating files and text of all kinds

Macros, mutli-line editing, directory editing, remote editing over SSH... Emacs is my swiss army knife for text transformations. There are large chunks of my config that deal with sharpening various blades of said swiss army knife.

* Keybindings
* System and editor settings
* Interface tweaks

* Implementation  
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:

** Prerequisites and setup
:PROPERTIES:
:noweb-ref: Prerequisites and setup -- load basic support libraries, set some useful variables
:CUSTOM_ID: setup
:END:  
*** First, load common lisp libraries

#+name: setup-require-cl :comments both
#+begin_src emacs-lisp
(require 'cl)
#+end_src

*** Then set our path appropriately.

I use a somewhat gross hack to grab the $PATH environment variable from my ~/.bashrc and use this. This way my path is consistent between Emacs and my shell elsewhere.

#+name: setup-path :comments both
#+begin_src emacs-lisp
(let ((jcs:shell-path (shell-command-to-string ". ~/.bashrc; echo -n $PATH")))
  (setenv "PATH" jcs:shell-path)
  (setq exec-path (split-string jcs:shell-path ":")))
#+end_src
 
*** Set a few variables for directories

Define our home directory, dot emacs directory (where the config lives), emacs binary directory (where Emacs.app lives), and info file directory.

I use these =*-dir= variables all over the place in my config.

#+name: setup-dirs :comments both
#+begin_src emacs-lisp
(setq home-dir "/Users/jstautz/"
      dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name)))
      emacs-dir "/Applications/Emacs.app/Contents/"
      emacs-bin (concat emacs-dir "MacOS/Emacs")
      info-dir (concat emacs-dir "Resources/info/"))
#+end_src

*** Tell 'customize' where to save changes

Emacs has a neat customize feature, accessible via =M-x customize=, which lets you modify user-configurable variables in a simpler (read: non-elisp) interface.

I don't generally use it -- I prefer to =setq= these variables in my init files manually -- but sometimes I'll fiddle with settings in customize to try things out.

When I do so, I'd like customize to save things at the bottom of my init-customizations.el file. If I like the changes, I'll pull them out of the customize section of this file and place them in the appropriate places in my config.

#+name: setup-custom-file
#+begin_src emacs-lisp
(setq custom-file (concat dotemacs-dir "init-customizations.el"))
#+end_src

**** TODO depending on how I change the file structure, I may aim this at a different file

*** Add .emacs.d to load-path

#+name: setup-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path dotemacs-dir)
#+end_src

*** Finally, decrypt secrets.el.gpg

Passwords, private URLs, and personal info are encrypted and stored in the secrets.el.gpg file. Emacs decrypts this using the keys in my .gnupg keyring.

I do this before I begin loading packages so that package configs can access variables stored in the secrets file.

#+name: setup-decrypt-secrets-function
#+begin_src emacs-lisp
(defun jcs:decrypt-secrets ()
  (interactive)
  (require 'secrets))
#+end_src

** Keybindings
:PROPERTIES:
:noweb-ref: Keybindings
:CUSTOM_ID: keybindings
:END:
** Sync and load packages
:PROPERTIES:
:noweb-ref: Sync external packages with el-get, load them, and configure them
:CUSTOM_ID: load-packages
:END:
Here's the good stuff!

*** Set package sources
I want to add a few other sources (notably marmalade and melpa) to my package source list
  
#+name: packages-set-sources
#+begin_src emacs-lisp
(require 'package)
(dolist (source '( ("gnu" . "http://elpa.gnu.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("melpa" . "http://melpa.milkbox.net/packages/")))
  (add-to-list 'package-archives source t))
(package-initialize)
#+end_src

*** Add ELPA and el-get package directories to load path  

#+name: packages-add-to-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path (concat dotemacs-dir "elpa"))
(add-to-list 'load-path (concat dotemacs-dir "el-get/el-get"))
#+end_src

 
*** Bootstrap el-get

#+name: packages-el-get-bootstrap
#+begin_src emacs-lisp
;; el-get, install thyself!
(unless (require 'el-get nil t)
 (url-retrieve
  "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
  (lambda (s)
    (let ((el-get-master-branch) (el-get-install-skip-emacswiki-recipes))
      (goto-char (point-max))
      (eval-print-last-sexp)))))
#+end_src

And set some directory vars

#+name: packages-set-el-get-dirs
#+begin_src emacs-lisp
(setq el-get-dir (concat dotemacs-dir "el-get")
      el-get-user-package-directory (concat dotemacs-dir "config"))
#+end_src


 
*** Load packages
#+name: init-packages
#+begin_src emacs-lisp
(require 'init-packages)
#+end_src

** Customizations
:PROPERTIES:
:noweb-ref: Load some editor customizations, UI tweaks, and custom keybindings
:CUSTOM_ID: customizations
:END:

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-customizations)
#+end_src

** Custom functions and tweaks
:PROPERTIES:
:noweb-ref: Load a bunch of custom functions
:CUSTOM_ID: custom-functions
:END:

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-custom-functions)
#+end_src
** Final steps
:PROPERTIES:
:noweb-ref: Post-flight: load Emacs desktop and start server
:CUSTOM_ID: final-steps
:END:
*** Restore my desktop

I'm not sure why this is required now when it wasn't before -- something slightly different after changing my config.

#+name: desktop-read
#+begin_src emacs-lisp
(desktop-read)
#+end_src


*** start server
Now that everything's good to go, start the emacs server so we can connect to it using =emacsclient= from the command line

#+name: server-start
#+begin_src emacs-lisp
(server-start)
#+end_src
* Additional implementation details

This section contains some less-interesting details that I won't be modifying all that often, but were still important to document. These include:

- How init.el loads this config
- The final structure of 

** Structure of my .emacs.d/ 
:PROPERTIES:
:CUSTOM_ID: structure
:END:

My .emacs.d directory looks a little something like this:

- =.emacs.d/=
  - =init.el=
    - Loaded automatically by Emacs on startup. Fires up org-mode and loads =emacs-init.org.=
  - =emacs-init.org=
    - The document you're reading right now. Contains documentation with embedded elisp configuration.
  - =init-org.org=
    - [[file::init-org.org][Documentation & elisp for my org-mode setup.]] I've separated this into its own config file because I want to be able to export and publish it separately.
  - =secrets.el=
    - Loads secrets.el.pgp -- an encrypted file containing passwords and sensitive info.
  - =config/=
    - Configs for each package live here for now [they will be folded into emacs-init.org].
    - =init-*.org=
    - =init-*.el=
  - =el-get/= 
    - I use el-get to install and update external packages. Each package gets installed in its own directory inside the =el-get/= directory.
** =init.el=

The elisp in this file only has one purpose: set things up to load the rest of my configuration via org-babel.

The important part is that last s-expression:

#+begin_src emacs-lisp :tangle no
(org-babel-load-file (expand-file-name "emacs-init.org" dotemacs-dir))
#+end_src 

This line will export ("tangle") the code blocks from the =emacs-init.org= file into a file called =emacs-init.el=, then load that file.

Before we do that, however, we need to make sure org-mode and its org-babel libraries are fully loaded. This is easy enough on the face of it -- Emacs comes with org-mode built in. 

However, I'm running the latest version of org-mode (installed & maintained w/ el-get) and my config depends on some of its more recent features. This means I've got to load org-mode from the el-get directory:

#+begin_src emacs-lisp :tangle no
(setq org-mode-dir (concat dotemacs-dir "el-get/org-mode/"))

(if (file-directory-p (concat org-mode-dir "lisp"))
    (progn
      (add-to-list 'load-path (concat org-mode-dir "lisp"))
      (add-to-list 'load-path (concat org-mode-dir "contrib/lisp"))
      (require 'org)
      (require 'ob-tangle)
      (require 'org-id))
  (message "Could not load org-mode! Expecting it in the el-get/org-mode directory."))
#+end_src


*** Right, but how does this work if el-get hasn't yet been run?
I'm deliberately ignoring the chicken-and-the-egg problem here:

- My setup uses org-mode to load its config.
- My setup also uses el-get to fetch and install external packages.
- Using el-get, I can take a bare clone of my repo and (theoretically) just launch Emacs... and el-get will find, install, and configure all external packages.
- One of these external packages is org-mode.

If I'm doing a fresh install, the el-get directory won't exist and we won't be able to load org-mode.

I've tried using Emacs 24.3.50's built-in version of org-mode, but it doesn't work with my config. This might change with Emacs 24.4 -- I'll need to check that out soon.

Big question, though:

- If I use el-get to install packages, but I rely on org-mode in order to load my configs that install packages... Would it make sense to keep org-mode separate from other el-get packages (ie. directly included in my config repo)? /Probably.../

** =emacs-init.org=

This is the meat of my emacs config. It's also the document you're reading right now.

When this document is tangled and loaded by org-babel, all the elisp code snippets contained within it are re-arranged and loaded. 

That re-arranging bit is important. Expressions in my config file need to be in a particular order for Emacs to understand them. But I also want to be able to document them in =emacs-init.org= in a totally different order -- one that makes sense to a human reader.

I can define that Emacs-friendly code order here, using "noweb" syntax, which looks something like:

#+begin_src emacs-lisp :tangle yes :noweb tangle
<<Prerequisites and setup -- load basic support libraries, set some useful variables>>
<<Sync external packages with el-get, load them, and configure them>>
<<Load some editor customizations, UI tweaks, and custom keybindings>>
<<Load a bunch of custom functions>>
<<Post-flight: load Emacs desktop and start server>>
#+end_src

I try to treat the resulting =emacs-init.el= file almost like /compiled code/. It's the machine-readable file that I never really look at. 

Any edits or changes, even if they're experimental, should be made in the org-mode files instead of directly in the .el files. This way, I'm ensuring my documentation always stays up to date. I'm explaining changes as I make them rather than documenting them after the fact.

*** TODO possible bug with noweb and comments
If I set =comments noweb=, the links generated in the code don't seem to correctly link. Noweb-referenced code sections have empty file/search links. Would be best if they linked to the custom_id perperty of the subtree they're in.

** =el-get/= and =config/=

I used to find and install third-party elisp packages manually. This got nasty pretty quickly.

Emacs 24 introduced a really nice package management system. I used it for a while on its own, then supplemented it with [[https://github.com/dimitri/el-get][el-get]].

El-get is a little like homebrew for Emacs. It lets you install and manage packages from multiple sources (MELPA, github, Emacswiki, wherever), set dependencies, generate autoloads, etc. 

Packages loaded with el-get look for their configs in appropriately-named files in the =config/= directory. For example, markdown-mode looks for its settings in =config/init-markdown-mode.el=.

As I consolidate settings a little more in a literate configuration, I may pull these configs back into the el-get setup when possible.
* 
