#+TITLE: Jeff's Emacs config
#+AUTHOR: Jeff Stautz
#+EMAIL: jeff@jeffstautz.com
#+LANGUAGE:  en
#+OPTIONS: toc:nil num:t ^:nil

#+begin_quote
People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen -- the editor should get used to us.

-- [[http://blog.vivekhaldar.com/post/31970017734/new-frontiers-in-text-editing][Vivek Hadlar]]
#+end_quote

#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

** What is this?
:PROPERTIES:
:CUSTOM_ID: what_is_this
:END:

It's a [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] version of my Emacs config files.

My current setup borrows liberally from Emacs users far smarter than I am, including:
- [[http://doc.norang.ca/org-mode.html][Bernt Hansen]] 
- [[https://github.com/eschulte/emacs24-starter-kit][Eric Schulte]]
- [[https://github.com/magnars/.emacs.d][Magnar Sveen]]
- [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua]]
- [[https://github.com/technomancy/dotfiles][Phil Hagelberg]]
- [[https://github.com/bodil/emacs.d][Bodil Stokke]]
- [[http://www.masteringemacs.org/][Mickey Petersen]]
- And a ton of others. 

Props and praises are scattered throughout my config in places where I can remember who I stole something from.

** Disclaimers and Warnings
:PROPERTIES:
:CUSTOM_ID: disclaimer
:END:

You /don't/ want to try and use my configs straight out of the box. 

- This is a perpetual work in progress. 
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies, and there are probably a bunch of undocumented dependencies.
- Requires Emacs 24.3. Only tested on Mac OS X.
- First load will require an internet connection to download packages (this will take a while).
- I'm not responsible if any of this blows up on you.

** What the hell is literate programming?
:PROPERTIES:
:CUSTOM_ID: what_is_literate
:END: 

Short answer: instead of writing separate documentation, the documentation /contains/ the program. 

Or as Knuth puts it:

#+begin_quote 
Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to humans what we want the computer to do.

-- Donald E. Knuth, Literate Programming, 1984
#+end_quote

The document you're reading now is an [[http://org-mode.org][org-mode]] text file[fn:1] that contains both code and documentation. 

On startup, emacs pulls out ("tangles") the code snippets in this file and uses them to configure the editor.

[fn:1] Okay, technically you're reading HTML that's exported from the org-mode text file. The point is that the *source file* that I edit when I update my Emacs config *is the documentation.* The elisp is compiled (tangled) from the documentation org-mode files. Org-mode files can be exported in a number of nifty formats, including HTML.

-------------------------------------

** Why use literate programming for my Emacs config?
:PROPERTIES:
:CUSTOM_ID: why-literate
:END:

It's an experiment. We'll see how well it works out.

I've been inspired by [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua's literate emacs config]], as well as by [[http://doc.norang.ca/org-mode.html][Bernt Hansen's amazingly thorough and detailed documentation of his org-mode setup]].

Using a literate programming approach has a number of advantages that appeal to me:

1. *Better organization of my .emacs lisp files*
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure.
   - I'm able to add headers and subsections to better organize my code -- way better than using giant banner-style comment blocks or squirreling things away in separate files all over the place.
   - My configuration is easier to read and understand.
2. *I'm better able to follow my own thought processes.*
   - Code is organized according to how I think, not how the interpreter thinks -- I can explain code snippets in an order that makes sense to me, and org-babel later compiles these into the correct order.
   - Explanations take priority, code is secondary.
   - When I revisit code I wrote ten years ago, I have a hope of understanding not just what it does, but /what the hell I was thinking./
3. *Sharing my setup is easier*
   - Org-mode's publishing features mean that it's pretty simple to export my documentation and publish it.
   - I have one file that generates nice-looking documentation and the code itself.
   - Even better: more detailed explanations of my code mean it's easier for others to understand it and benefit from it.
     
** License
:PROPERTIES:
:CUSTOM_ID: license
:END:

I don't actually need a license for this, but I feel /way/ cooler having one here.

#+begin_example
Copyright (C)  2014  Jeff Stautz

Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts.
  
Code in this document is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.
  
This code is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
#+end_example 

This document (including HTML format or raw org-mode format) is licensed under the GNU Free Documentation License version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

The code examples and CSS stylesheets are licensed under the GNU General Public License v3 or later (http://www.gnu.org/licenses/gpl.html).

* Structure of my .emacs.d/ 
:PROPERTIES:
:CUSTOM_ID: structure
:END:

First, some basics about how all this works.

My .emacs.d directory looks a little something like this:

- =.emacs.d/=
  - =init.el= -- Loaded automatically by Emacs on startup. Fires up org-mode and loads =emacs-init.org.=
  - =emacs-init.org= -- The document you're reading right now. Contains documentation with embedded elisp configuration.
  - =init-org.org= -- [[file::init-org.org][Documentation & elisp for my org-mode setup.]] I've separated this into its own config file because I want to be able to export and publish it separately.
  - =secrets.el= -- Loads secrets.el.pgp -- an encrypted file containing passwords and sensitive info.
  - =config/= -- Configs for each package live here for now [they will be folded into emacs-init.org].
    - =init-*.org=
    - =init-*.el=
  - =el-get/= -- I use el-get to install and update external packages. Each package gets installed in its own directory inside the =el-get/= directory.

** =init.el=

This is the first file that Emacs loads on startup. It bootstraps the rest of my config by loading it via org-babel.

My init.el currently looks like this:

#+begin_src emacs-lisp :tangle no
(setq dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name))))

;; Assume that org-mode is installed via el-get
(setq org-mode-dir (concat dotemacs-dir "el-get/org-mode/"))

;; Load the necessary bits of org-mode and org-babel
(if (file-directory-p (concat org-mode-dir "lisp"))
    (progn
      (add-to-list 'load-path (concat org-mode-dir "lisp"))
      (add-to-list 'load-path (concat org-mode-dir "contrib/lisp"))
      (require 'org)
      (require 'ob-tangle)
      (require 'org-id))
  (message "Could not load org-mode! Expecting it in the el-get/org-mode directory."))

;; Load the rest of my config from org-mode file
(org-babel-load-file (expand-file-name "emacs-init.org" dotemacs-dir))
#+end_src

The important part is that last s-expression:

#+begin_src emacs-lisp :tangle no
(org-babel-load-file (expand-file-name "emacs-init.org" dotemacs-dir))
#+end_src 

This line will export ("tangle") the code blocks from the =emacs-init.org= file into a file called =emacs-init.el=, then load that file.

Before we do that, however, we need to make sure org-mode and its org-babel libraries are fully loaded. 

Note that my setup requires a later version of org-mode than the one pre-installed with Emacs 24.3. My config is pointed at the latest version (installed & maintained with el-get).

This is a little sloppier than I'd like[fn:2], but I'm leaving it in place until I have time to sort out a better option.

[fn:2] I'm deliberately ignoring the chicken-and-the-egg problem here:

- My setup uses org-mode to load its config.
- My setup also uses el-get to fetch and install external packages.
- Using el-get, I can take a bare clone of my repo and (theoretically) just launch Emacs... and el-get will find, install, and configure all external packages.
- One of these external packages is org-mode.

If I'm doing a fresh install, the el-get directory won't exist and we won't be able to load org-mode.

I've tried using Emacs 24.3.50's built-in version of org-mode, but it doesn't work with my config. This might change with Emacs 24.4 -- I'll need to check that out soon.

Big question, though:

- If I use el-get to install packages, but I rely on org-mode in order to load my configs that install packages... Would it make sense to keep org-mode separate from other el-get packages (ie. directly included in my config repo)? /Probably.../

-------------------------------------

** =emacs-init.org=

The emacs-init.org file is the meat of my emacs config. It's also the document you're reading right now.

When this document is tangled and loaded by org-babel, all the elisp code snippets contained within it are re-arranged and loaded. 

That re-arranging bit is important. Expressions in my config file need to be in a particular order for Emacs to understand them. But I also want to be able to document them in =emacs-init.org= in a totally different order -- one that makes sense to a human reader.

I can define that Emacs-friendly code order here, using "noweb" syntax[fn:3], which looks something like:

#+begin_src emacs-lisp :tangle yes :noweb tangle
<<Prerequisites and setup -- load basic support libraries, set some useful variables>>
<<Sync external packages with el-get, load them, and configure them>>
<<Tweak some UI settings>>
<<Load some editor customizations>>
<<Set custom keybindings>>
<<Load a bunch of custom functions>>
<<Post-flight: load Emacs desktop and start server>>
#+end_src

When I tangle this file, the noweb headers above will be expanded to the matching sections of elisp. 

I try to treat the resulting =emacs-init.el= file like /compiled code/. It's the machine-readable file that I never really look at. 

Any edits or changes, even if they're experimental, are made in the org-mode files instead of directly in the .el files. This way, I'm ensuring my documentation always stays up to date. I'm explaining changes as I make them rather than documenting them after the fact.

[fn:3] Found a possible bug with noweb and comments. 

If I set =comments noweb=, the links generated in the code don't seem to correctly link. Noweb-referenced code sections have empty file/search links. It would be best if they linked to the custom_id property of the subtree they're in. Might be something I can hack on and fix later.

-------------------------------------

** =el-get/= and =config/= directories

Back in the dark ages, I would find third-party elisp packages on the interwebs and install them manually. This got nasty pretty quickly.

    - My emacs repo got bloated and disorganized
    - I could never rememember where I grabbed packages from
    - Updating packages was a chore

Emacs 24 introduced a really nice package management system. I used it for a while on its own, then supplemented it with [[https://github.com/dimitri/el-get][el-get]].

El-get takes some getting used to, but it's super powerful. Think of it like [[http://http://brew.sh/][homebrew]] for Emacs. 

It lets you install and manage packages from multiple sources (MELPA, github, Emacswiki, wherever), set dependencies, generate autoloads, etc.

I don't keep *any* of my installed packages under version control at the moment. If I install Emacs config from scratch, el-get will bootstrap itself and start downloading/loading all the packages I need.[fn:4]

Packages loaded with el-get look for their configs in appropriately-named files in the =config/= directory. For example, markdown-mode looks for its settings in =config/init-markdown-mode.el=.

As I consolidate settings a little more in a literate configuration, I may pull these configs back into the el-get setup when possible.


[fn:4] In theory. In practice this doesn't always work out. 

Usually on first startup, el-get is downloaded and loaded, but it fails to progress any further than that. Killing emacs and re-opening it then starts the process of grabbing packages. This also sometimes fails partway. 

A few rounds of killing/re-opening emacs usually gets through all packages.

This is something I should dig into further and fix.

-------------------------------------

* Interface tweaks
:PROPERTIES:
:noweb-ref: Tweak some UI settings
:END:

I know, I know. Emacs doesn't have much of an interface to begin with. 

Even so, there are a couple of changes I like to make in order to make things a little cleaner.

** Remove distracting UI elements

Emacs comes with a fat ugly toolbar turned on by default. It's seriously gross looking. 

Turning it off is one of the first things I do.

#+name: UI-toolbar
#+begin_src emacs-lisp 
(tool-bar-mode -1)
#+end_src

I don't really use the side fringe at all, so I set to a colour that blends into the buffer background. I happen to use Emacs with dark text on a white background, so I set the fringe to white. 

#+name: UI-fringe
#+begin_src emacs-lisp 
(custom-set-faces '(fringe ((t (:background"white")))))
#+end_src

Scroll bars are also pretty useless in this age of scroll wheels and trackpads, so I turn that off as well.

The only *good* part about a scroll bar? Its size and position give you a quick visual indication of how far down in the current file you are, and how large the file is.

I make up for this by [[file://emacs-init.org][displaying a position indicator in my modeline]] -- I'll explain that setup a bit further down.

#+name: UI-fringe
#+begin_src emacs-lisp 
(scroll-bar-mode -1)

#+end_src

** Hide welcome messages

We're all professionals, here. We know what we're doing. 

So let's ditch the splash screen, the startup message, and the default text on the scratch buffer:

#+name: UI-splash
#+begin_src emacs-lisp 
(setq inhibit-splash-screen 1)               
(setq initial-scratch-message "")
(setq inhibit-startup-message t)

#+end_src 

** Kill some annoyances

Seriously, screw the audible alert bell.

Let's set the ring-bell function to an empty function instead of the deafult (which is named, appropriately, =ding=).

Let's also turn on the visible-bell option so that the screen blinks/alerts me.

#+name: UI-bells
#+begin_src emacs-lisp 
(setq ring-bell-function (lambda ()))
(setq visible-bell 1)                        

#+end_src

Another obnoxious default to change: the requirement that you actually type the letters "y" "e" and "s" at a yes/no prompt. Whose dumb idea was that? 

This s-exp lets you just type "y" or "n" like in any other sane application:

#+name: UI-yorn
#+begin_src emacs-lisp 
(fset 'yes-or-no-p 'y-or-n-p)

#+end_src


** Highlight cursor location

I realize a lot of people hate blinking cursors, but I like them because:

- It lets me quickly find my cursor on a large screen
- The persistent blinking indicates Emacs is waiting for my input -- it's pushing me to write, to get shit done. 

#+name: UI-cursor
#+begin_src emacs-lisp 
(setq blink-cursor-mode t)
#+end_src

Another helpful inidicator: I like having my current line highlighted. =grey93= is nice and subtle against a white background.

#+name: UI-highlight-line
#+begin_src emacs-lisp 
(global-hl-line-mode 1)
(set-face-background 'hl-line "grey93")

#+end_src

** Cursor scroll settings

Let's make buffer scrolling / paging a bit more sane.

By default, Emacs will recenter on the cursor when you scroll above / below the current viewable area. This leads to some disorienting jumping around.

Setting =scroll-conservatively= to a value > 100 means automatic scrolling will never center on the cursor.

#+name: UI-scroll-conserv
#+begin_src emacs-lisp 
(setq scroll-conservatively 1000)
#+end_src

The =scroll-margin= variable controls how close to the bottom/top edge of the frame I can get before the viewable area begins to scroll. I like to get right up to the bottom edge before scrolling.

#+name: UI-scroll-margin
#+begin_src emacs-lisp 
(setq scroll-margin 0)
#+end_src

I don't want to jump around at all when scrolling up or down.

And when I *do* page up or down, I want my cursor to be in the same position relative to the top and bottom of the frame.

This just makes sense: When I page up or down with =M-v= or =C-v= I shouldn't have to hunt for my cursor. I should still be looking at it.

#+name: UI-scroll-agg
#+begin_src emacs-lisp 
(setq scroll-up-aggressively nil
      scroll-down-aggressively nil
      scroll-preserve-screen-position t)

#+end_src

** Mac-specific settings

#+name: UI-mac-settings
#+begin_src emacs-lisp 
;; Make mouse/keyboard/EOL/clipboard work sanely on OS X
(setq mac-emulate-three-button-mouse t)
(setq ns-alternate-modifier (quote meta))
(setq ns-command-modifier (quote meta))
(setq eol-mnemonic-mac "(Mac)")
(setq x-select-enable-clipboard t)

;; If I drag n' drop a file onto Emacs, visit the file (instead of append to buffer)
(define-key global-map [ns-drag-file] 'ns-find-file) 
#+end_src

** Show both line and column numbers

A basic feature of any decent text editor: show me what line number I'm on.

The column number display isn't as useful but does come in handy.

#+name: UI-linum
#+begin_src emacs-lisp 
(line-number-mode 1)                         
(column-number-mode 1)

#+end_src
** Confirm before quitting Emacs

I want to make sure I don't accidentally kill Emacs. Ever. 

I do this by changing two things:

1) Unset =C-x C-c= so I don't hit it accidentally, and
2) Prompt me to confirm that I actually want to quit.

If I want to quit Emacs (gasp!) I now need to do it *very* deliberately via =M-x save-buffers-kill-emacs= and then confirm.

Good thing I rarely quit Emacs.

#+name: UI-quit-emacs
#+begin_src emacs-lisp
(global-unset-key "\C-x\C-c")
(setq confirm-kill-emacs 'y-or-n-p)

#+end_src

** Connecting to Emacs server shouldn't pop up frames

Speaking of rarely quitting Emacs... My preferred way of working is in a single fullscreen frame in Emacs.app that's open all the time, running as a server. 

If I'm working in the terminal and I need to edit a file in my current directory, I can just do:

#+begin_example 
$> emacsclient filename.txt
#+end_example

This will open filename.txt within my already-running Emacs.app instance. Sweet.[fn:5]

One thing I had to tweak for this: I want to make sure connecting via emacsclient doesn't spawn a new frame for editing -- I want to use the existing frame.

#+name: UI-pop-up-frames
#+begin_src emacs-lisp 
(setq ns-pop-up-frames nil)

#+end_src

[fn:5] I actually aliased emacsclient to =em= in bash to make this even simpler. =$>em filename.txt= drops me into my existing already-running Emacs session and visits the file.

-------------------------------------

** Force redisplay

If the =redisplay-dont-pause= variable is not set, then any keyboard/mouse event will stop a screen redraw to handle the input. Which I suppose made sense on older machines or slower networks.

On modern machines, turning this on should make the display feel faster.

Thanks to [[http://www.masteringemacs.org/articles/2011/10/02/improving-performance-emacs-display-engine/][Mickey Peterson for this one]].

#+name: UI-redisplay
#+begin_src emacs-lisp 
(setq redisplay-dont-pause t)

#+end_src

I believe this is now on by default in Emacs 24, so I may no longer need to set this explicitly.

* Keybindings
:PROPERTIES:
:noweb-ref: Set custom keybindings
:END:

#+name: keybindings
#+begin_src emacs-lisp 
;; Up yours, read-only toggle!
(global-unset-key "\C-x\C-q")

;; Rebind M-s to save-buffer -- I never center lines
(global-set-key (kbd "M-s") 'save-buffer)

;; Don't think I need this, if I set it globally?
;; (add-hook 'text-mode-hook
;;  (lambda ()
;;  (define-key text-mode-map (kbd "M-s") 'save-buffer)
;;  )
;; )

;; Rebind M-o to other-window. C-x o is too clunky.
(global-set-key (kbd "M-o") 'other-window)

;; Bind C-esc to 'top-level for exiting from debugger, etc.
(global-set-key (kbd "<C-escape>") 'top-level)  
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(add-hook 'org-mode-hook
          (lambda()
            (define-key org-mode-map (kbd "<escape>") 'keyboard-escape-quit)))

;; I like Undo here.
(global-set-key (kbd "C-z") 'undo)     

;; I also like iBuffer here
(global-set-key "\C-x\C-b" 'ibuffer)

;; I hit F2 accidentally way too often
(global-unset-key (kbd "<f2>"))     

;; Scroll buffer
(global-set-key "\M-n" 'scroll-up-line)
(global-set-key "\M-p" 'scroll-down-line)

;; Return should preserve indentation (will override in modes where I don't like this)
(global-set-key (kbd "RET") 'newline-and-indent)

;; wdired toggle -- for rewriting filenames. hit 'r' in dired mode
;; any reason why this has to be eval'ed after load?
(eval-after-load 'dired
  '(define-key dired-mode-map "r"
     'wdired-change-to-wdired-mode))


;; If I scroll with my mouse wheel on the fringe/margin, handle this:
(global-set-key (kbd "<left-margin><wheel-down>") 'mwheel-scroll)
(global-set-key (kbd "<left-margin><wheel-up>") 'mwheel-scroll)
(global-set-key (kbd "<right-margin><wheel-down>") 'mwheel-scroll)
(global-set-key (kbd "<right-margin><wheel-up>") 'mwheel-scroll)

#+end_src



* Editor customizations
:PROPERTIES:
:noweb-ref: Load some editor customizations
:END:

#+name: editor-settings
#+begin_src emacs-lisp 
;;-----------------------------------------------------------------------------
;; System / Editing Prefs
;;-----------------------------------------------------------------------------

;; Set gabage collection threshold higher, as per https://github.com/lewang/flx
(setq gc-cons-threshold 20000000)

;; Put backups & autosaves in their place (not in current dir)
(defvar backup-dir (concat home-dir ".emacs.backup/"))
(defvar autosave-dir (concat home-dir ".emacs.autosave/"))
(setq backup-directory-alist `((".*" . ,backup-dir)))
(setq auto-save-file-name-transforms `((".*" ,autosave-dir t)))

;; Make backups of files, even when they're in version control
(setq vc-make-backup-files t)

;; When deleting files, move them to Trash
(setq delete-by-moving-to-trash t)
(setq trash-directory (concat home-dir ".Trash/"))

;; Refresh any buffer when file on disk changes
(setq global-auto-revert-mode 1)

;; ...Also auto refresh dired, but be quiet about it
(setq global-auto-revert-non-file-buffers t)
(setq auto-revert-verbose nil)

;; ...Also rebuild Tags files, and be quiet about it
(setq tags-revert-without-query t)

;; M-x locate uses OS X's Spotlight
(setq locate-make-command-line (lambda (s) `("mdfind" "-name" ,s)))


;; Tabs insert 4 spaces, sentences have one space (as God intended).
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(setq sentence-end-double-space nil)

;; selection options + rectangle selection w/ CUA
(transient-mark-mode t)
(delete-selection-mode t)
(setq cua-enable-cua-keys nil)               
(cua-mode t)

;; auto-fill options 
(setq fill-column 120)
(setq default-fill-column 120)

;; Testing wrap-to-fill options instead of auto-fill
;; note: I think wrap-to-fill is only included in nxhtml-mode,
;;       so we need packages installed before this works.
;; 
;;(auto-fill-mode 1)
;;(add-hook 'text-mode-hook 'turn-on-auto-fill)
(wrap-to-fill-column-mode 1)
(add-hook 'text-mode-hook '(lambda() (wrap-to-fill-column-mode 1)))
(add-hook 'text-mode-hook 'turn-on-visual-line-mode)

;; Desktop saving options
(desktop-save-mode 1)
(setq desktop-globals-to-save
	  (append '((extended-command-history . 30)
				(file-name-history        . 100)
				(grep-history             . 30)
				(compile-history          . 30)
				(minibuffer-history       . 50)
				(query-replace-history    . 60)
				(read-expression-history  . 60)
				(regexp-history           . 60)
				(regexp-search-ring       . 20)
				(search-ring              . 20)
				(shell-command-history    . 50)
				tags-file-name
				register-alist)))

;; Quick ways to restore desktop/windows
(winner-mode 1)

;; Bookmark options
(setq bookmark-default-file (concat dotemacs-dir "bookmarks"))

;; spellcheck options
(setq ispell-program-name "aspell")

;; Tramp defaults
(setq tramp-default-method "ssh")

;; Make sure diff works with .org files and others
(setq diff-switches "-a -c")

;; Let me upcase/downcase regions
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)

;; ignore case when completing, including filenames
(setq completion-ignore-case t           
  read-file-name-completion-ignore-case t)

;; Let me narrow to region -- I use this a bunch
(put 'narrow-to-region 'disabled nil)



#+end_src


* What I use Emacs for
:PROPERTIES:
:CUSTOM_ID: what-i-do-in-emacs
:END:

#+begin_quote
This is my rifle. There are many like it, but this one is mine.

--Major General William H. Rupertus, "The Rifleman's Creed," 1942
#+end_quote

In order to understand why I've configured things the way I did, it might help to understand some things I do in Emacs.

** Org-mode

I spend 90% of my time in Emacs inside [[http://orgmode.org/][org-mode]]. 

I've been using it for several years for taking notes, planning, writing, and tracking my to-do lists. I've got a [[file:./init-org.org][whole section of my Emacs config dedicated to the ins and outs of my org-mode configuration.]]

It's gnarly. It's complicated. It involves a lot of yak-shaving. It's ripe for refactoring. But it /works/ for me. 

** Writing Fiction

For the last 9 years, I've done most of my writing, editing, and revising in plain text within Emacs.

Sometimes I work in [[https://daringfireball.net/projects/markdown/][Markdown syntax]] and view the formatted version of my stories in [[http://markedapp.com/][Marked.app]].

Other times I write using minimal [[http://www.latex-project.org/][LaTeX markup]], which I then run through a perl script to add full LaTeX document headers for exporting.

The details of [[file:./emacs-init.org][how I use Emacs for fiction writing are documented later in this file]]. 

** Programming

Unlike most Emacs users, I'm not a professional software engineer. 

I've done a bunch of development work in the past, and I enjoy messing around in code occasionally. I dabble. I pretend like I know what I'm doing. But I'm nowhere near professional.

[[http://hootsuite.com/careers/][I work with a ton of talented engineers every day at HootSuite]] and they constantly inspire me to learn more, try more, and hack more. 

When I grow up maybe I'll be an engineer.

A couple of languages I work with in Emacs:

- I work with Emacs lisp quite a bit (of course)
- I'm learning python
- I play around with javascript (and HTML/CSS, obviously)

[[file::./emacs-init.org][My Emacs settings for software development]] should be taken with several grains of salt -- these parts of my config aren't very mature and I'm probably doing everything wrong.

** Manipulating files and text of all kinds

Macros, mutli-line editing, directory editing, remote editing over SSH... Emacs is my Swiss Army Knife for text transformations. 

[[file:./emacs-init.org][There are large chunks of my config]] that deal with sharpening various blades of said Swiss Army Knife.

* System and editor settings
* Implementation  
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:

** Keybindings
:PROPERTIES:
:noweb-ref: Keybindings
:CUSTOM_ID: keybindings
:END:
** Sync and load packages
:PROPERTIES:
:noweb-ref: Sync external packages with el-get, load them, and configure them
:CUSTOM_ID: load-packages
:END:
Here's the good stuff!

*** Set package sources
I want to add a few other sources (notably marmalade and melpa) to my package source list
  
#+name: packages-set-sources
#+begin_src emacs-lisp
(require 'package)
(dolist (source '( ("gnu" . "http://elpa.gnu.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("melpa" . "http://melpa.milkbox.net/packages/")))
  (add-to-list 'package-archives source t))
(package-initialize)
#+end_src

*** Add ELPA and el-get package directories to load path  

#+name: packages-add-to-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path (concat dotemacs-dir "elpa"))
(add-to-list 'load-path (concat dotemacs-dir "el-get/el-get"))
#+end_src

 
*** Bootstrap el-get

#+name: packages-el-get-bootstrap
#+begin_src emacs-lisp
;; el-get, install thyself!
(unless (require 'el-get nil t)
 (url-retrieve
  "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
  (lambda (s)
    (let ((el-get-master-branch) (el-get-install-skip-emacswiki-recipes))
      (goto-char (point-max))
      (eval-print-last-sexp)))))
#+end_src

And set some directory vars

#+name: packages-set-el-get-dirs
#+begin_src emacs-lisp
(setq el-get-dir (concat dotemacs-dir "el-get")
      el-get-user-package-directory (concat dotemacs-dir "config"))
#+end_src


 
** Load packages
#+name: init-packages
#+begin_src emacs-lisp
(require 'init-packages)
#+end_src

* Custom functions and tweaks
:PROPERTIES:
:noweb-ref: Load a bunch of custom functions
:CUSTOM_ID: custom-functions
:END:


Really, I think I can organize things into some better categories:
- General UI / Editor configs
  - remove gross UI elements
    - Hide toolbar
    - Hide scrollbar
    - Hide fringe
  - hide welcome messages
  - remove alert bells
  - y-or-n
  - confirm before quit
  - emacs server/client settings
- General editing
  - highlight cursor location & line
  - cursor-scroll settings
  - mac command & option -> meta
  - mac EOL chars
  - mac clipboard
  - 3-button mouse emulation
  - drag-n-drop files
  - delete moves to trash
  - mac spotlight
  - line + column number settings
  - CUA/rectagle
  - transient mark
  - delete-selection
  - auto-fill columns
  - wrap + wrap-to-fill
  - desktop-save options
  - ignore case when completing
  - activate narrow-to-region
  - unbind f2, read-only-toggle
  - bind M-s for save
  - bind C-z undo
  - fix scroll events for fringe
  - bind RET to ret+indent
  - bind C-esc -> top level
  - winner-mode on
  - bind M-o other window
  - custom window-splitting and moving functions
  - switch between split window and single frame
  - shift between windows
  - shrink/expand windows
  - bind M-n, M-p scroll view
  - bind C-X C-b ibuffer
  - dired, bind r to wdired
  - dired: end/beginning of buffer bindings
  - isearch with initial content
  - ace-jump
  - browse kill ring 
  - kill-ring-search
  - easy-kill
  - also xah's kill-ring-save functions
  - zap-to-char
  - rename current buffer file, delete current file
  - guide key (UI)
  - ido (UI)
  - ido ubiquitous
  - ido vertical
  - popwin (UI)
  - smart-mode-line (UI)
  - diminish (UI)
  - smex (UI)
- Org-mode / PIM related
  - org dir settings
  - org alist
  - org modules
  - ... etc
  - Calendar + cal sync functions
  - jcs:clock in/out functions
- Writing-related
  - backup files
  - tabs 4 spaces, sentences 2 spaces
  - spellcheck
  - Marked.app
  - unfill paragraph
  - package: writer-names
  - package: fountain-mode
  - package: wordsmith-mode
  - markdown-mode
- Programming-related
  - auto-revert
  - tags options
  - find-tag functions that refresh TAGS files
  - tramp options
  - reopen buffer as root via tramp
  - auto-recomplile lisp being worked on
  - diff options
  - function: eval-and-replace
  - package: auto-complete
  - python: jedi, virtualenvwrapper
  - html/javascript: js2, js2refactor, nxhtml
  - package: restclient
  - package: psvn
  - package: skewer-mode
  - package: yasnippet
- System settings / prerequisites / post-flight
  - pre-reqs
    - cl libs
    - set path
    - directory vars
    - customize file
    - load path
    - decrypt secrets file
  - GC settings
  - force redisplay
  - post-flight
    - desktop
    - start-server

I think organizing it by use cases is better.




#+name: init-packages
#+begin_src emacs-lisp

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; A random smattering of custom/helper functions
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;-----------------------------------------------------------------------------
;; jcs:getcals -- Sync my Google Calendars to emacs diary
;;-----------------------------------------------------------------------------
(require 'icalendar)

(defun getcal (url)
  "Download ics file and add to diary"
  (let ((tmpfile (url-file-local-copy url)))
    (icalendar-import-file tmpfile "~/org/calendar.diary" t)
    (kill-buffer (car (last (split-string tmpfile "/"))))
    )
  )

;; Grab google calendars from secrets.el.gpg
(defun jcs:getcals ()
  (interactive)
  (if (not (boundp 'google-calendars))
      (jcs:decrypt-secrets))
    (find-file "~/org/calendar.diary")
    (flush-lines "^[& ]")
    (dolist (url google-calendars) (getcal url))
    (kill-buffer "calendar.diary"))


;;-----------------------------------------------------------------------------
;; jcs:clock functions -- Functions to clock into/out of  a particular item in
;; projects.org (OR create a new item and clock into it)
;;-----------------------------------------------------------------------------
 (defun jcs:clock-in-to-string (theString &optional theCategory)
  "Clock into a particular item in ~/org/projects.org file. Takes optional Category param."
  (interactive)
  (save-excursion
	(let (filepath filename mybuffer)
	  (setq filepath "/Users/jstautz/org/projects.org"
            filename (file-name-nondirectory filepath)
            mybuffer (find-file filepath))
	  (goto-char (point-min))
	  (widen) 
	  ;; if no category defined, try to find string in file and clock in
	  (if (eq theCategory nil)
		  (if (search-forward theString nil t)
			  (org-clock-in)
			;; if not found in buffer, insert new item at end and clock into it
			(goto-char (point-max))
			(insert (concat "*** " theString))
			(goto-char (point-max))
			(org-clock-in))
		;; thecategory is non-nil, so this is a new item w/ category
		(goto-char (point-max))
		(insert (concat "*** " theString "\n  :PROPERTIES:\n  :CATEGORY: " theCategory "\n  :END:\n"))
		(goto-char (point-max))
		(org-clock-in)))))

(defun jcs:clock-out (&optional theString theCategory)
  (org-clock-out))


;;-----------------------------------------------------------------------------
;; Eval and replace -- replace current sexp with its value
;;-----------------------------------------------------------------------------

(defun eval-and-replace ()
  "Replace the preceding sexp with its value."
  (interactive)
  (backward-kill-sexp)
  (prin1 (eval (read (current-kill 0)))
         (current-buffer)))

(global-set-key (kbd "C-c e") 'eval-and-replace)


;;-----------------------------------------------------------------------------
;; i-search with initial contents.
;; original src: http://platypope.org/blog/2007/8/5/a-compendium-of-awesomeness
;;-----------------------------------------------------------------------------
(defvar isearch-initial-string nil)

(defun isearch-set-initial-string ()
  (remove-hook 'isearch-mode-hook 'isearch-set-initial-string)
  (setq isearch-string isearch-initial-string)
  (isearch-search-and-update))

(defun isearch-forward-at-point (&optional regexp-p no-recursive-edit)
  "Interactive search forward for the symbol at point."
  (interactive "P\np")
  (if regexp-p (isearch-forward regexp-p no-recursive-edit)
    (let* ((end (progn (skip-syntax-forward "w_") (point)))
           (begin (progn (skip-syntax-backward "w_") (point))))
      (if (eq begin end)
          (isearch-forward regexp-p no-recursive-edit)
        (setq isearch-initial-string (buffer-substring begin end))
        (add-hook 'isearch-mode-hook 'isearch-set-initial-string)
        (isearch-forward regexp-p no-recursive-edit)))))

(global-set-key (kbd "C-c C-s") 'isearch-forward-at-point)


;;-----------------------------------------------------------------------------
;; Nice functions to change copy-kill region to copy or kill current line
;; if no active region.
;; Stolen from http://xahlee.org/emacs/emacs_copy_cut_current_line.html
;;-----------------------------------------------------------------------------
(defadvice kill-ring-save (before slick-copy activate compile)
  "When called interactively with no active region, copy the current line."
  (interactive
   (if mark-active
       (list (region-beginning) (region-end))
     (progn
       (message "Current line copied to kill-ring.")
       (list (line-beginning-position) (line-beginning-position 2)) ) ) ))

(defadvice kill-region (before slick-copy activate compile)
  "When called interactively with no active region, cut the current line."
  (interactive
   (if mark-active
       (list (region-beginning) (region-end))
     (progn
       (list (line-beginning-position) (line-beginning-position 2)) ) ) ))


;;-----------------------------------------------------------------------------
;; Make zap-to-char act more like "zap-up-to-char"
;; Thanks to Eric Himmelreich
;; http://rawsyntax.com/blog/learn-emacs-use-defadvice-modify-functions/
;;-----------------------------------------------------------------------------
(defadvice zap-to-char (after my-zap-to-char-advice (arg char) activate)
  "Kill up to the ARG'th occurence of CHAR, and leave CHAR.
  The CHAR is replaced and the point is put before CHAR."
  (insert char)
  (forward-char -1))


;;-----------------------------------------------------------------------------
;; Window-splitting and moving functions
;; Thanks to Ignacio Paz Posse
;; http://ignaciopp.wordpress.com/2009/05/23/emacs-manage-windows-split/
;;-----------------------------------------------------------------------------

;; Instead of giving me two identical buffers when I split the window, give me the previous buffer.
;; From http://www.reddit.com/r/emacs/comments/25v0eo/you_emacs_tips_and_tricks/chldury
(defun vsplit-last-buffer ()
  (interactive)
  (split-window-vertically)
  (other-window 1 nil)
  (switch-to-next-buffer)
  )
(defun hsplit-last-buffer ()
  (interactive)
   (split-window-horizontally)
  (other-window 1 nil)
  (switch-to-next-buffer)
  )

(global-set-key (kbd "C-x 2") 'vsplit-last-buffer)
(global-set-key (kbd "C-x 3") 'hsplit-last-buffer)


;; Switch (zoom) between split window config and a single window
(defun toggle-windows-split()
  "Switch back and forth between one window and whatever split of
windows we might have in the frame. The idea is to maximize the
current buffer, while being able to go back to the previous split
of windows in the frame simply by calling this command again."
  (interactive)
  (if (not(window-minibuffer-p (selected-window)))
      (progn
        (if (< 1 (count-windows))
            (progn
              (window-configuration-to-register ?u)
              (delete-other-windows))
          (jump-to-register ?u)))))

(define-key global-map (kbd "C-`") 'toggle-windows-split)
(define-key global-map (kbd "C-~") 'toggle-windows-split)

;; Window shifting. C-x-o lets us go forward a window (or several).
;; This one lets us go back one or more windows. From Glickstein.
(defun other-window-backward (&optional n)
  "Select previous Nth window."
  (interactive "P")
  (other-window (- (prefix-numeric-value n))))

(global-set-key [prior] 'other-window)
(global-set-key [next] 'other-window-backward)
(global-set-key [(control tab)] 'other-window)
(global-set-key [(shift control tab)] 'other-window-backward)

;; Also (stolen from someone else's dot file) this is used to shrink/expand windows without using the mouse.
(define-key global-map (kbd "C-M-<left>") 'shrink-window-horizontally)
(define-key global-map (kbd "C-M-<right>") 'enlarge-window-horizontally)
(define-key global-map (kbd "C-M-<up>") 'enlarge-window)
(define-key global-map (kbd "C-M-<down>") 'shrink-window)


;;-----------------------------------------------------------------------------
;; Open in Marked.app -- Stolen from https://github.com/mattsears/emacs
;;-----------------------------------------------------------------------------
(defun markdown-preview-file ()
  "run Marked on the current file and revert the buffer"
  (interactive)
  (shell-command
   (format "open -a /Applications/Marked.app %s"
           (shell-quote-argument (buffer-file-name)))))

(global-set-key "\C-cm" 'markdown-preview-file)


;;-----------------------------------------------------------------------------
;; Unfill paragraph -- From https://raw.github.com/qdot/conf_emacs/master/emacs_conf.org
;;-----------------------------------------------------------------------------
(defun unfill-paragraph ()
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))

;;-----------------------------------------------------------------------------
;; Re-open buffer as root -- Thank to @christopherdone: http://t.co/KiAWcJoo
;;-----------------------------------------------------------------------------
(defun tramp-sudo-reopen ()
  "Re-open the current with tramp."
  (interactive)
  (let ((file-name (format "/sudo:localhost:%s" (buffer-file-name)))
        (line (line-number-at-pos))
        (column (current-column)))
    (kill-buffer)
    (find-file file-name)
    (goto-line line)
    (goto-char (+ (point) column))))


;;-----------------------------------------------------------------------------
;; auto-recompile elisp -- Thanks to Adolfo Benedetti and Xah Lee
;;-----------------------------------------------------------------------------
(defun byte-compile-current-buffer ()
  "`byte-compile' current buffer if it's emacs-lisp-mode and compiled file exists."
  (interactive)
  (when (and (eq major-mode 'emacs-lisp-mode)
             (file-exists-p (byte-compile-dest-file buffer-file-name)))
    (byte-compile-file buffer-file-name)))

(add-hook 'after-save-hook 'byte-compile-current-buffer)


;;-----------------------------------------------------------------------------
;; A smarter find-tag that automagically reruns etags when it can't find a
;; requested item and then makes a new try to locate it.
;; by Jonas.Jarnestrom<at>ki.ericsson.se
;; Fri Mar 15 09:52:14 2002
;;-----------------------------------------------------------------------------
(defadvice find-tag (around refresh-etags activate)
  "Rerun etags and reload tags if tag not found and redo find-tag.
   If buffer is modified, ask about save before running etags."
  (let ((extension (file-name-extension (buffer-file-name))))
    (condition-case err
        ad-do-it
      (error (and (buffer-modified-p)
                  (not (ding))
                  (y-or-n-p "Buffer is modified, save it? ")
                  (save-buffer))
             (er-refresh-etags extension)
             ad-do-it))))

(defun er-refresh-etags (&optional extension)
  "Run etags on all peer files in current dir and reload them silently."
  (interactive)
  (shell-command (format "etags *.%s" (or extension "el")))
  (let ((tags-revert-without-query t))  ; don't query, revert silently
    (visit-tags-table default-directory nil)))

;; While we're at it, modify pop-tag-mark to stay centered on cursor
(defadvice pop-tag-mark (after my-pop-tag-mark-advice activate)
  "After popping back to where find-tag was invoked,
   center screen on cursor"
  (let ((current-prefix-arg '(4)))
  (call-interactively 'recenter-top-bottom)))


;;-----------------------------------------------------------------------------
;; Renaming and deleting files should be easier to do. 
;; C-x C-r renames current file
;; C-x C-k deletes current file (since C-x k kills the buffer)
;;-----------------------------------------------------------------------------

(defun rename-current-buffer-file ()
  "Renames current buffer and file it is visiting."
  (interactive)
  (let ((name (buffer-name))
        (filename (buffer-file-name)))
    (if (not (and filename (file-exists-p filename)))
        (error "Buffer '%s' is not visiting a file!" name)
      (let ((new-name (read-file-name "New name: " filename)))
        (if (get-buffer new-name)
            (error "A buffer named '%s' already exists!" new-name)
          (rename-file filename new-name 1)
          (rename-buffer new-name)
          (set-visited-file-name new-name)
          (set-buffer-modified-p nil)
          (message "File '%s' successfully renamed to '%s'"
                   name (file-name-nondirectory new-name)))))))

(global-set-key (kbd "C-x C-r") 'rename-current-buffer-file)


(defun delete-current-buffer-file ()
  "Removes file connected to current buffer and kills buffer."
  (interactive)
  (let ((filename (buffer-file-name))
        (buffer (current-buffer))
        (name (buffer-name)))
    (if (not (and filename (file-exists-p filename)))
        (ido-kill-buffer)
      (when (yes-or-no-p "Are you sure you want to remove this file? ")
        (delete-file filename t)
        (kill-buffer buffer)
        (message "File '%s' successfully removed" filename)))))

(global-set-key (kbd "C-x C-k") 'delete-current-buffer-file)


;;-----------------------------------------------------------------------------
;; Make beginning-of-buffer and end-of-buffer work nicely in dired
;; Thanks to @magnars
;;-----------------------------------------------------------------------------

(defun dired-back-to-top ()
  (interactive)
  (beginning-of-buffer)
  (dired-next-line 4))

(define-key dired-mode-map
  (vector 'remap 'beginning-of-buffer) 'dired-back-to-top)

(defun dired-jump-to-bottom ()
  (interactive)
  (end-of-buffer)
  (dired-next-line -1))

(define-key dired-mode-map
  (vector 'remap 'end-of-buffer) 'dired-jump-to-bottom)
#+end_src
* Other Implementation details

This section contains some less-interesting details that I won't be modifying all that often, but were still important to document. 

** Prerequisites and setup
:PROPERTIES:
:noweb-ref: Prerequisites and setup -- load basic support libraries, set some useful variables
:CUSTOM_ID: setup
:END:  

This section contains the first bits of elisp in my config that get loaded. 

*** First, let's load common lisp libraries

This is generally a good idea.

#+name: setup-require-cl :comments both
#+begin_src emacs-lisp
(require 'cl)

#+end_src

*** Then set our path appropriately.

This is kind of a gross hack to grab the $PATH environment variable from my ~/.bashrc and use this. This way my path is consistent between Emacs and my shell elsewhere.

#+name: setup-path :comments both
#+begin_src emacs-lisp
(let ((jcs:shell-path (shell-command-to-string ". ~/.bashrc; echo -n $PATH")))
  (setenv "PATH" jcs:shell-path)
  (setq exec-path (split-string jcs:shell-path ":")))

#+end_src
 
*** Set a few variables for directories

Define our home directory, dot emacs directory (where the config lives), emacs binary directory (where Emacs.app lives), and info file directory.

I use these =*-dir= variables all over the place in my config.

#+name: setup-dirs :comments both
#+begin_src emacs-lisp
(setq home-dir "/Users/jstautz/"
      dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name)))
      emacs-dir "/Applications/Emacs.app/Contents/"
      emacs-bin (concat emacs-dir "MacOS/Emacs")
      info-dir (concat emacs-dir "Resources/info/"))
#+end_src

*** Tell 'customize' where to save changes

Emacs has a neat customize feature, accessible via =M-x customize=, which lets you modify user-configurable variables in a simpler (read: non-elisp) interface.

I don't generally use it -- I prefer to =setq= these variables in my init files manually -- but sometimes I'll fiddle with settings in customize to try things out.

When I do so, I'd like customize to save things in a separate =emcas-custom= file. I treat this file as temporary storage. If I like the changes, I'll pull them out of this file and place them in the appropriate places in my config.

#+name: setup-custom-file
#+begin_src emacs-lisp
(setq custom-file (concat dotemacs-dir "emacs-custom.el"))

#+end_src

*** Add .emacs.d to load-path

Kinda necessary.

#+name: setup-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path dotemacs-dir)
#+end_src

*** Finally, decrypt secrets.el.gpg

Passwords, private URLs, and personal info are encrypted and stored in the secrets.el.gpg file. Emacs decrypts this using the keys in my .gnupg keyring.

I do this before I begin loading packages so that package configs can access variables stored in the secrets file.

#+name: setup-decrypt-secrets-function
#+begin_src emacs-lisp
(defun jcs:decrypt-secrets ()
  (interactive)
  (require 'secrets))

#+end_src


** Post-flight -- final steps
:PROPERTIES:
:noweb-ref: Post-flight: load Emacs desktop and start server
:CUSTOM_ID: final-steps
:END:
*** Restore my desktop

I'm not sure why this is required now when it wasn't before -- something slightly different after changing my config.

#+name: desktop-read
#+begin_src emacs-lisp
(desktop-read)
#+end_src

*** Start server
Now that everything's good to go, start the emacs server so we can connect to it using =emacsclient= from the command line.

#+name: server-start
#+begin_src emacs-lisp
(server-start)
#+end_src
