#+TITLE: Jeff's .emacs -- Init file
#+OPTIONS: toc:2 num:nil ^:nil

#+begin_quote
  People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen - the editor should get used to us.

  -- [[http://blog.vivekhaldar.com/post/31970017734/new-frontiers-in-text-editing][Vivek Hadlar]]
#+end_quote

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

*** What is this?

A [[http://en.wikipedia.org/wiki/Literate_programming][Literate Programming]] version of my Emacs config files.

My current setup borrows liberally from Emacs users far smarter than I am, including:
- [[https://github.com/magnars/.emacs.d][Magnar Sveen]]
- [[http://doc.norang.ca/org-mode.html][Bernt Hansen]] 
- [[https://github.com/eschulte/emacs24-starter-kit][Eric Schulte]]
- [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua]]
- [[https://github.com/technomancy/dotfiles][Phil Hagelberg]]
- And a ton of others I'm forgetting.

*** Disclaimers and Warnings

You probably *don't* want to try and use my configs straight out of the box. 

- This is a perpetual work in progress. 
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies, and there are probably a bunch of undocumented dependencies.
- Requires Emacs 24.3. Only tested on Mac OS X.
- First load will require an internet connection to download packages (this will take a while).


*** What I use Emacs for

**** Org-mode

I spend 90% of my time in Emacs inside org-mode. I've been using it for several years for taking notes, planning, writing, and tracking my to-do lists. I've got a whole section of my Emacs config dedicated to the ins and outs of my [[file:./config/init-org-mode.el][org-mode configuration.]]

**** Writing Fiction

For the last 9 years, I've done most of my writing, editing, and revising in plain text within Emacs.

Instead of using Microsoft Word or Pages, I write in plain text using either:
1. [[https://daringfireball.net/projects/markdown/][Markdown syntax]], and viewing the formatted results in [[http://markedapp.com/][Marked.app]]
2. Minimal [[http://www.latex-project.org/][LaTeX markup]], which I then run through a perl script to add full LaTeX document headers.

The details of how I use Emacs for fiction writing are [[file:./emacs-init.org][documented here]].

**** Programming

I love hacking around and pretending like I know how to program. A couple of languages I use:

- I work with Elisp quite a bit (of course)
- I'm learning python
- I play around with javascript (and HTML/CSS)

My Emacs settings for software dev should be taken with several grains of salt -- these parts of my config aren't very mature and I'm probably doing everything wrong.

**** Manipulating files and text of all kinds

Macros, mutli-line editing, directory editing, remote editing over SSH... Emacs is my swiss army knife for text transformations.

*** Structure 
   :PROPERTIES:
   :CUSTOM_ID: structure
   :END:
The =init.el= file is loaded automatically by Emacs on startup. It fires up org-mode and then loads the elisp snippets embedded in this emacs-init.org file.

Packages are loaded using el-get. Configurations for each package live in the /config/init-package-name.el files -- each of these loads the corresponding package-config.org file to configure the package.



**** .emacs.d directory structure




**** how things get loaded
**** 

* Implementation  
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:

*** Prerequisites and setup  
***** First, load common lisp libraries

#+name: setup-require-cl
#+begin_src emacs-lisp
(require 'cl)
#+end_src

*** Then set our path appropriately.

I use a somewhat gross hack to grab the $PATH environment variable from my ~/.bashrc and use this. This way my path is consistent between Emacs and my shell elsewhere.

#+name: setup-path :comments both
#+begin_src emacs-lisp
  (let ((jcs:shell-path (shell-command-to-string ". ~/.bashrc; echo -n $PATH")))
    (setenv "PATH" jcs:shell-path)
    (setq exec-path (split-string jcs:shell-path ":")))
#+end_src


******* TODO replace the above with $PATH? 
***** Set a few variables for directories

Define our home directory, dot emacs directory (where the config lives), emacs binary directory (where Emacs.app lives), and
info file directory.

I use these =*-dir= variables all over the place in my config.

#+name: setup-dirs
#+begin_src emacs-lisp
(setq home-dir "/Users/jstautz/"
      dotemacs-dir (file-name-directory (or load-file-name (buffer-file-name)))
      emacs-dir "/Applications/Emacs.app/Contents/"
      emacs-bin (concat emacs-dir "MacOS/Emacs")
      info-dir (concat emacs-dir "Resources/info/"))
#+end_src

***** Tell 'customize' where to save changes

Emacs has a neat customize feature, accessible via =M-x customize=, which lets you modify user-configurable variables in
a simpler (read: non-elisp) interface.

I don't generally use it -- I prefer to =setq= these variables in my init files manually -- but sometimes I'll fiddle
with settings in customize to try things out.

When I do so, I'd like customize to save things at the bottom of my init-customizations.el file. If I like the changes,
I'll pull them out of the customize section of this file and place them in the appropriate places in my config.

#+name: setup-custom-file
#+begin_src emacs-lisp
(setq custom-file (concat dotemacs-dir "init-customizations.el"))
#+end_src

******* TODO depending on how I change the file structure, I may aim this at a different file

***** Add .emacs.d to load-path

#+name: setup-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path dotemacs-dir)
#+end_src

***** Finally, decrypt secrets.el.gpg

Passwords, private URLs, and personal info are encrypted and stored in the secrets.el.gpg file. Emacs decrypts this
using the keys in my .gnupg keyring.

I do this before I begin loading packages so that package configs can access variables stored in the secrets file.

#+name: setup-decrypt-secrets-function
#+begin_src emacs-lisp
(defun jcs:decrypt-secrets ()
  (interactive)
  (require 'secrets))
#+end_src

*** Keybindings
*** Sync and load packages

Here's the good stuff!

***** Set package sources
I want to add a few other sources (notably marmalade and melpa) to my package source list
  
#+name: packages-set-sources
#+begin_src emacs-lisp
(require 'package)
(dolist (source '( ("gnu" . "http://elpa.gnu.org/packages/")
                   ("elpa" . "http://tromey.com/elpa/")
                   ("marmalade" . "http://marmalade-repo.org/packages/")
                   ("melpa" . "http://melpa.milkbox.net/packages/")))
  (add-to-list 'package-archives source t))
(package-initialize)
#+end_src

***** Add ELPA and el-get package directories to load path  

#+name: packages-add-to-load-path
#+begin_src emacs-lisp
(add-to-list 'load-path (concat dotemacs-dir "elpa"))
(add-to-list 'load-path (concat dotemacs-dir "el-get/el-get"))
#+end_src

 
***** Bootstrap el-get

#+name: packages-el-get-bootstrap
#+begin_src emacs-lisp
;; el-get, install thyself!
(unless (require 'el-get nil t)
 (url-retrieve
  "https://raw.github.com/dimitri/el-get/master/el-get-install.el"
  (lambda (s)
    (let ((el-get-master-branch) (el-get-install-skip-emacswiki-recipes))
      (goto-char (point-max))
      (eval-print-last-sexp)))))
#+end_src

And set some directory vars

#+name: packages-set-el-get-dirs
#+begin_src emacs-lisp
(setq el-get-dir (concat dotemacs-dir "el-get")
      el-get-user-package-directory (concat dotemacs-dir "config"))
#+end_src


 
***** Load packages
#+name: init-packages
#+begin_src emacs-lisp
(require 'init-packages)
#+end_src

*** Customizations

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-customizations)
#+end_src

*** Custom functions and tweaks

#+name: init-packages
#+begin_src emacs-lisp
(require 'init-custom-functions)
#+end_src
*** Final steps

***** Restore my desktop

I'm not sure why this is required now when it wasn't before -- something slightly different after changing my config.

#+name: desktop-read
#+begin_src emacs-lisp
(desktop-read)
#+end_src


***** start server
Now that everything's good to go, start the emacs server so we can connect to it using =emacsclient= from the command line

#+name: server-start
#+begin_src emacs-lisp
(server-start)
#+end_src
* Scraps 





ideas stolen from various places around the internet, hundreds of tiny tweaks and fiddles, and a few hand-written hunks of elisp of which I am not entirely proud.
With special thanks to


I've recently reworked my .emacs files to follow a [[http://en.wikipedia.org/wiki/Literate_programming][literate programming]] paradigm. 

Org-mode files (such as this one) provide the explanations, notes, and thought processes behind my configuration.

The emacs lisp code blocks embedded within these org-mode files are loaded to perform the actual configuration.

The advantages to this approach are:

1. Better organization of my .emacs lisp files
   - My elisp code snippets are embedded within the fold-able goodness of org-mode's outline structure
   - I'm able to add headers and subsections to better organize my code
   - My configuration is easier to read and understand -- it also looks good on github!

2. I'm better able to follow my own thought processes
   - Code is organized according to how I think, not how the interpreter thinks
   - Explanations take priority, code is secondary
   - Documentation can be more thorough than regular code comments
