#+Title: .emacs.d README
#+AUTHOR: Jeff Stautz

* My emacs config 

Contains dozens of ideas stolen from various places around the internet, hundreds of tiny tweaks and fiddles, and a
few hand-written hunks of elisp of which I am not entirely proud.

Makes heavy use of [[http://github.com/dimitri/el-get][el-get]] to manage and install packages. On first load, el-get *should* bootstrap & install itself.

Very [[http://orgmode.org/][org-mode]] heavy. My org-mode setup is ugly and complicated and personal -- you'll probably want to change a lot of it.

*** Disclaimers
- Requires Emacs 24. Only tested on Mac OS X.
- Makes use of the [[https://gist.github.com/1397155][ns-toggle-fullscreen patch]] for Emacs 24.
- First load will require an internet connection to download packages (this will take a while).
- No attempts have been made to make this setup portable. It's full of weird environment idiosyncracies.
- secrets.el.gpg is an encrypted store containing passwords, etc. You'll want to replace that with your own.
- A perpetual work in progress, currently undergoing some heavy refactoring.
